docs: application-api.md
vuejs/docs-next-zh-cn pull request #160
Opened 2020-10-02 15:05 UTC by watonyweng

# ⚠️⚠️⚠️ DISCLAIMER ⚠️⚠️⚠️:

Thanks for your interest in submitting a PR! At this time, because the docs are in beta, the team is currently in the midst of changes. As a result, **we are not ready for additional contributions yet**.

## How can I provide feedback?

To be respectful of your time and ideas, **please [create an issue](https://github.com/vuejs/docs-next/issues/new) instead of a pull request**. Otherwise, we will have to simply close your pull request at this time.

Thanks for your understanding!
#159

2020-10-13 05:14 UTC, veaba commented on src/api/application-api.md
> +// 注册一个名为my-component的组件
原文是：`register an options object` ，这里是否需要根据上下文语境来描述的必要吗？@Justineo

2020-10-13 06:06 UTC, Justineo requested changes

2020-10-13 06:06 UTC, Justineo commented on src/api/application-api.md
> +在 Vue 3 中，改变全局 Vue 行为的 API 现在被移动到了由新的 `createApp` 方法所创建的应用实例上。此外，现在它们的影响仅限于该特定应用实例：
```suggestion
在 Vue 3 中，全局改变 Vue 行为的 API 现在被移到了由新的 `createApp` 方法所创建的应用实例上。此外，现在它们的影响仅限于该特定应用实例：
```

“全局改变”我认为不需要改动，意思应该是“（以）全局（的方式）改动”。

2020-10-13 06:06 UTC, Justineo commented on src/api/application-api.md
> +#### prevNode
```suggestion
#### prevNode
```

2020-10-16 01:35 UTC, watonyweng commented on src/api/application-api.md
> +// 注册一个名为my-component的组件
那我保留原来的翻译

2020-10-24 06:58 UTC, merged