style: Unified style
vuejs/docs-next-zh-cn pull request #203
Opened 2020-10-19 07:34 UTC by FAKER-A

## Description of Problem

## Proposed Solution

## Additional Information

2020-10-19 07:50 UTC, veaba commented
感谢你的 PR，前面第一个 commit，尽管这是一个很小的语法错误，但检查到英文版没有这个改动，建议你先去英文版发起这个改动后中文版才会合并。

这个 PR 暂时挂起。

2020-10-19 07:52 UTC, FAKER-A commented
> 感谢你的 PR，前面第一个 commit，尽管这是一个很小的语法错误，但检查到英文版没有这个改动，建议你先去英文版发起这个改动后中文版才会合并。
> 
> 这个 PR 暂时挂起。

好的， 感谢回复！

2020-10-19 16:57 UTC, veaba commented
@FAKER-A 

关于加粗符号内的符号使用，请参考我们之前讨论的 #78 。（这里[影响翻译的迁移到右侧](#78)，[半角符号转换全角符号的wiki](https://github.com/vuejs/docs-next-zh-cn/wiki/%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A#%E6%A0%87%E7%82%B9%E7%AC%A6%E5%8F%B7)）

另外稍微麻烦下，后面的更改顺便把 <sub>标签的内容移除下，尽量保持原本一致，这是历史遗留的翻译所致。

2020-10-19 17:02 UTC, veaba requested changes

2020-10-19 17:02 UTC, veaba commented on src/guide/migration/custom-elements-interop.md
> +- **BREAKING：** 特定 `is` prop 用法仅限于保留的 `<component>` 标记
```suggestion
- **非兼容**：特定 `is` prop 用法仅限于保留的 `<component>` 标记。
```

2020-10-19 17:02 UTC, veaba commented on src/guide/migration/custom-elements-interop.md
> +- **NEW：** 有了新的 `v-is` 指令来支持 2.x 用例，其中在原生元素上使用了 `v-is` 来处理原生 HTML 解析限制。
```suggestion
- **新**：有了新的 `v-is` 指令来支持 2.x 用例，其中在原生元素上使用了 `v-is` 来处理原生 HTML 解析限制。
```

2020-10-19 17:02 UTC, veaba commented on src/guide/migration/custom-elements-interop.md
> +- **BREAKING：** 特定 `is` prop 用法仅限于保留的 `<component>` 标记
see #62

2020-10-19 17:02 UTC, veaba commented on src/guide/migration/custom-elements-interop.md
> +- **NEW：** 有了新的 `v-is` 指令来支持 2.x 用例，其中在原生元素上使用了 `v-is` 来处理原生 HTML 解析限制。
see #62

2020-10-20 03:34 UTC, FAKER-A commented on src/guide/migration/custom-directives.md
>  - **beforeUpdate**:<sup style="color:green">新的！</sup>这是在元素本身更新之前调用的，很像组件生命周期钩子
> @FAKER-A
> 
> 关于加粗符号内的符号使用，请参考我们之前讨论的 #78 。（这里[影响翻译的迁移到右侧](#78)，[半角符号转换全角符号的 wiki](https://github.com/vuejs/docs-next-zh-cn/wiki/%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A#%E6%A0%87%E7%82%B9%E7%AC%A6%E5%8F%B7)）
> 
> 另外稍微麻烦下，后面的更改顺便把 `<sub>` 标签的内容移除下，尽量保持原本一致，这是历史遗留的翻译所致。
> 
> 关于 “breaking” 的问题见 #62

已针对上述问题进行了修改。

2020-10-20 03:34 UTC, FAKER-A commented
> @FAKER-A
> 
> 关于加粗符号内的符号使用，请参考我们之前讨论的 #78 。（这里[影响翻译的迁移到右侧](#78)，[半角符号转换全角符号的 wiki](https://github.com/vuejs/docs-next-zh-cn/wiki/%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A#%E6%A0%87%E7%82%B9%E7%AC%A6%E5%8F%B7)）
> 
> 另外稍微麻烦下，后面的更改顺便把 `<sub>` 标签的内容移除下，尽量保持原本一致，这是历史遗留的翻译所致。
> 
> 关于 “breaking” 的问题见 #62

已针对上述问题进行了修改

2020-10-20 03:42 UTC, FAKER-A commented
> 感谢你的 PR，前面第一个 commit，尽管这是一个很小的语法错误，但检查到英文版没有这个改动，建议你先去英文版发起这个改动后中文版才会合并。
> 
> ~这个 PR 暂时挂起。~
> 
> 下面提出了一些修改意见~~

https://github.com/vuejs/docs-next/pull/636#issue-505775937

> 感谢你的 PR，前面第一个 commit，尽管这是一个很小的语法错误，但检查到英文版没有这个改动，建议你先去英文版发起这个改动后中文版才会合并。
> 
> ~这个 PR 暂时挂起。~
> 
> 下面提出了一些修改意见~~
第一个commit已合并到英文版
https://github.com/vuejs/docs-next/pull/636#issue-505775937

2020-10-20 05:46 UTC, veaba approved these changes

2020-10-20 05:46 UTC, veaba commented on src/guide/migration/custom-directives.md
> +- update → 移除！有太多的相似之处要更新，所以这是多余的，请改用 `updated`
```suggestion
- update → 移除！有太多的相似之处要更新，所以这是多余的，请改用 `updated`。
```

2020-10-20 05:51 UTC, merged