docs: translate proxy
vuejs/docs-next-zh-cn pull request #230
Opened 2020-10-26 05:47 UTC by veaba

- 全局处理 `proxy`、`Proxy`、`proxied`、`Proxies` ，处理方式，保留其原始版本，大小写一致，仅做时态转换。
- 来源 #217
- 处理 #218 Suggested change

2020-10-26 05:58 UTC, Justineo commented
动词是不是要翻译一下？被 proxy 的 proxy 这种表达感觉不太 OK

2020-10-26 06:34 UTC, veaba commented
> 动词是不是要翻译一下？被 proxy 的 proxy 这种表达感觉不太 OK

那麻烦Review 一下哈~~ :pray:

虽然此前有结论，不过还是按实际语境来，后续补充到wiki中。

2020-10-28 10:04 UTC, Justineo requested changes

2020-10-28 10:04 UTC, Justineo commented on src/style-guide/README.md
> +6. **Local State** (本地的响应式 property)
```suggestion
6. **本地状态** (本地的响应式 property)
```

2020-10-28 10:22 UTC, veaba commented on src/guide/component-edge-cases.md
> +如果你发现自己需要在 Vue 中强制更新，在 99.99%的情况下，你在某个地方犯了错误。例如，你可能依赖于 Vue 响应性系统未跟踪的状态，比如在组件创建之后添加了 `data` 属性。
😂  后面这个`例如` 是不是要先给  英文 发个PR ？

这段话：

> 后面调用了 this.foo.bar = 1 这个不会触发响应式更新，但是在 Vue 3 里面已经没有这个限制了。

如果更感觉说的是根级没有提前加data 的 foo property.

2020-11-19 02:55 UTC, merged