Update custom-directive.md
vuejs/docs-next-zh-cn pull request #341
Opened 2021-01-02 03:10 UTC by Jinjiang

## Description of Problem

Translate the un-translated part of `custom-directive.md`

## Proposed Solution

## Additional Information

2021-01-02 06:34 UTC, veaba commented on src/guide/custom-directive.md
> +和[非 prop 的 attribute] 类似，当在组件中使用时，自定义指令总是会被应用在组件的根结点上。
```suggestion
和[非 prop 的 attribute] 类似，当在组件中使用时，自定义指令总是会被应用在组件的根节点上。
```

2021-01-02 06:34 UTC, veaba commented on src/guide/custom-directive.md
> +有了[片段](/guide/migration/fragments.html#概览)的支持，组件可以潜在地拥有多个根结点。当被应用在一个多根结点的组件上时，指令会被忽略，并且我们会抛出一个警告。
```suggestion
有了[片段](/guide/migration/fragments.html#概览)的支持，组件可以潜在地拥有多个根节点。当被应用在一个多根节点的组件上时，指令会被忽略，并且我们会抛出一个警告。
```

2021-01-02 06:36 UTC, veaba commented
现行的认知中，`node` 应该是翻译为 `节点` 吧，而非 `结点`

2021-01-03 03:28 UTC, Justineo requested changes

2021-01-03 03:28 UTC, Justineo commented on src/guide/custom-directive.md
> +和[非 prop 的 attribute] 类似，当在组件中使用时，自定义指令总是会被应用在组件的根节点上。
链接漏了

2021-01-03 03:28 UTC, Justineo commented on src/guide/custom-directive.md
> +有了[片段](/guide/migration/fragments.html#概览)的支持，组件可以潜在地拥有多个根节点。当被应用在一个多根节点的组件上时，指令会被忽略，并且我们会抛出一个警告。
```suggestion
有了[片段](/guide/migration/fragments.html#概览)支持以后，组件可能会有多个根节点。当被应用在一个多根节点的组件上时，指令会被忽略，并且会抛出一个警告。
```

2021-01-03 03:28 UTC, Justineo commented on src/guide/custom-directive.md
> +和[非 prop 的 attribute] 类似，当在组件中使用时，自定义指令总是会被应用在组件的根节点上。
链接漏了

2021-01-05 11:13 UTC, veaba approved these changes
approve

2021-01-05 11:14 UTC, merged