Keep mixin
vuejs/docs-next-zh-cn pull request #383
Opened 2021-01-24 03:51 UTC by ShroXd

## Description of Problem
#382 
## Proposed Solution
将所有 "混入" 替换为 “mixin”。为方便后续讨论修改，故将提交粒度细化为文件
## Additional Information
1. mixin 这个概念下，还有 mixin object 这个概念。目前将其翻译为了 `mixin 对象`
2. 将 混入 这个文档的标题也改成了 Mixin。这么做也许会导致原有的读者使用“混入”这个词搜索时搜索不到想要的内容，有待讨论

2021-01-24 04:37 UTC, veaba commented
在思考一个问题，仅当用于特性时候，保留原文，口头/行文动作之类的时候，译为中文利于读者理解其含义。

这个PR，全文做了替换，但阅读理解起来会比较晦涩。


比如：`methods 将被混入到组件实例中` ===> `methods 将被 mixin 到组件实例中` 。

@Jinjiang @Justineo

2021-01-24 10:33 UTC, ShroXd commented
> 
> 
> 在思考一个问题，仅当用于特性时候，保留原文，口头/行文动作之类的时候，译为中文利于读者理解其含义。
> 
> 这个PR，全文做了替换，但阅读理解起来会比较晦涩。
> 
> 比如：`methods 将被混入到组件实例中` ===> `methods 将被 mixin 到组件实例中` 。
> 
> @Jinjiang @Justineo

读起来的确很晦涩。
我觉得如果要根据词语的类型进行选择性翻译的话，`src/guide/mixins.md` 这部分的标题替换成 `混入（mixin）` 会比较好。这样读者就会理解这两个词是同样的概念，而不会产生误解。

2021-01-31 04:19 UTC, Jinjiang commented
我的建议和之前的 ref 类似，当*提及* mixin 的时候不必翻译，但是到了用自然语言*解释或描述* mixin 的时候，需要翻译，不然读者还是不明白是什么意思

2021-01-31 04:28 UTC, Jinjiang requested changes

2021-01-31 04:28 UTC, Jinjiang commented on src/api/application-api.md
> +  在整个应用范围内应用 `mixin`。一旦注册，它们就可以在当前的应用中任何组件模板内使用它。插件作者可以使用此方法将自定义行为注入组件。**不建议在应用代码中使用**。
```suggestion
  将一个 mixin 应用在整个应用范围内。一旦注册，它们就可以在当前的应用中任何组件模板内使用它。插件作者可以使用此方法将自定义行为注入组件。**不建议在应用代码中使用**。
```

不需要反斜杠，反斜杠仅用在展示代码的时候

2021-01-31 04:28 UTC, Jinjiang commented on src/api/options-data.md
> +  计算属性将被 mixin 到组件实例中。所有 getter 和 setter 的 `this` 上下文自动地绑定为组件实例。
这里英文原版其实没有讨论 mixin，原译法是对的

2021-01-31 04:28 UTC, Jinjiang commented on src/api/options-data.md
> +  methods 将被 mixin 到组件实例中。可以直接通过 VM 实例访问这些方法，或者在指令表达式中使用。方法中的 `this` 自动绑定为组件实例。
这里英文原版其实没有讨论 mixin，原译法是对的

2021-01-31 04:28 UTC, Jinjiang commented on src/guide/mixins.md
> +`mixin` 提供了一种非常灵活的方式，来分发 Vue 组件中的可复用功能。一个 `mixin` 对象可以包含任意组件选项。当组件使用 `mixin` 对象时，所有 `mixin` 对象的选项将被“混合”进入该组件本身的选项。
```suggestion
Mixin 提供了一种非常灵活的方式，来分发 Vue 组件中的可复用功能。一个 mixin 对象可以包含任意组件选项。当组件使用 mixin 对象时，所有 mixin 对象的选项将被“混合”进入该组件本身的选项。
```

2021-01-31 04:28 UTC, Jinjiang commented on src/guide/mixins.md
> +`mixin` 提供了一种非常灵活的方式，来分发 Vue 组件中的可复用功能。一个 `mixin` 对象可以包含任意组件选项。当组件使用 `mixin` 对象时，所有 `mixin` 对象的选项将被“混合”进入该组件本身的选项。
不必加额外的反引号，下同

2021-01-31 04:29 UTC, Jinjiang commented
> 我的建议和之前的 ref 类似，当_提及_ mixin 的时候不必翻译，但是到了用自然语言_解释或描述_ mixin 的时候，需要翻译，不然读者还是不明白是什么意思

我又仔细看了一下，英文版那里不是 mixin，只是自然语言描述“…… mixed into ……”。和 mixin 这个术语没有直接关系，不应该修改。

2021-01-31 07:28 UTC, ShroXd commented
抱歉在更改前忘记 rebase github fork 了，导致 git 历史一团糟。所以在本地更正后 force push 了

2021-01-31 10:07 UTC, Jinjiang approved these changes

2021-01-31 10:07 UTC, merged

2021-01-31 10:08 UTC, Jinjiang commented
> 抱歉在更改前忘记 rebase github fork 了，导致 git 历史一团糟。所以在本地更正后 force push 了

没关系，我用了 squash merge，所以最终的提及记录是比较干净的。