docs: proofread src/guide/migration/slots-unification.md
vuejs/docs-next-zh-cn pull request #395
Opened 2021-01-31 07:26 UTC by lumicia

## Description of Problem
[#394](https://github.com/vuejs/docs-next-zh-cn/issues/394)
## Proposed Solution

## Additional Information

2021-01-31 07:28 UTC, veaba commented
@lumicia   关于术语这块，请参考我们的 wiki  https://github.com/vuejs/docs-next-zh-cn/wiki/%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A

2021-01-31 07:32 UTC, lumicia commented
@veaba 好像没提到 slot，按 2.x 的中文文档翻译为插槽应该没问题吧。

2021-01-31 08:25 UTC, veaba commented
@Jinjiang @Justineo slot 应该出现分歧了。

也同 `mixin`、`ref`、`proxy`  出现类似的问题，`v3` 行文中大多数保留 `slot` 的原文，wiki 中并没有补齐此描述。 建议是 `v2` 、`v3` 译法都一致。

2021-01-31 08:26 UTC, veaba commented
@lumicia 稍等，在讨论此问题。

2021-03-06 05:14 UTC, Jinjiang commented
slot 之前是统一翻译成插槽的，我觉得可以统一到插槽

2021-03-08 14:56 UTC, veaba commented
@lumicia Hi，感谢等待，关于`slot` 的译法问题，现在有了新的进展，我们团队内部已达成一致意见，`slot` 往后统一翻译为 `插槽` （除了特殊语境下，比如: https://v3.cn.vuejs.org/api/built-in-components.html#slot）。

如果此前该 PR 因 `slot` 译法问题存在卡滞，现在你可以继续新的调整了。

关于这一 `slot` 译法问题的更多信息，请参考我们 #429 、#430。

2021-03-16 15:05 UTC, veaba commented on src/guide/migration/render-function-api.md
> -
这个应该有个换行符，不要删掉。

2021-03-16 15:25 UTC, veaba requested changes

2021-03-16 15:25 UTC, veaba commented on src/guide/migration/render-function-api.md
> +有关 `setup()` 如何工作的详细信息，请参考 [组合式 API 指南](/guide/composition-api-introduction.html)。
关于空格的使用，请参考我们的wiki，这里 `请参考 [组合` 之间不应该有空格。

2021-03-16 15:25 UTC, veaba commented on src/guide/migration/render-function-api.md
> + import { h, reactive } from 'vue'
这里不应该有空格开始的。

2021-03-16 15:25 UTC, veaba commented on src/guide/migration/render-function-api.md
> +## 已注册组件
可以改为：注册组件

2021-03-16 15:25 UTC, veaba commented on src/guide/migration/render-function-api.md
> +更多信息请参考 [渲染函数 API 更改 RFC](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0008-render-function-api-change.md#context-free-vnodes)。
```suggestion
更多信息请参考[渲染函数 API 更改 RFC](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0008-render-function-api-change.md#context-free-vnodes)。
```

2021-03-16 15:25 UTC, veaba commented on src/guide/migration/render-function-api.md
> + import { h, reactive } from 'vue'
```suggestion
import { h, reactive } from 'vue'
```

2021-03-16 15:25 UTC, veaba commented on src/guide/migration/render-function-api.md
> +有关 `setup()` 如何工作的详细信息，请参考 [组合式 API 指南](/guide/composition-api-introduction.html)。
```suggestion
有关 `setup()` 如何工作的详细信息，请参考[组合式 API 指南](/guide/composition-api-introduction.html)。
```

2021-03-16 15:25 UTC, veaba commented on src/guide/migration/render-function-api.md
> +## 已注册组件
```suggestion
## 注册组件
```

2021-03-17 14:35 UTC, merged