sync: #91a4425
vuejs/docs-next-zh-cn pull request #436
Opened 2021-03-19 16:01 UTC by veaba

## 本次同步说明
- 范围：(efbbe59——91a4425)[https://github.com/vuejs/docs-next/compare/efbbe59...91a4425]
- 关于新的翻译文档领取（https://github.com/vuejs/docs-next-zh-cn/projects/3）
- 新增的文档：
  - src/guide/ssr/introduction.md
  - src/guide/ssr/getting-started.md
  - src/guide/migration/suspense.md
  - src/guide/migration/props-data.md
  - src/guide/migration/mount-changes.md
- 大幅度改动的文档：src/guide/reactivity.md

2021-05-04 16:29 UTC, Justineo requested changes

2021-05-04 16:29 UTC, Justineo commented on src/api/global-api.md
> +<!-- translation: TODO -->
翻译过了？

2021-05-04 16:29 UTC, Justineo commented on src/api/global-api.md
> +允许在 [`setup`](/api/composition-api.html#setup) 的[单文件组件](/guide/single-file-component.html)函数中访问 CSS 模块。
CSS Module，实际上是一个特指的技术项目，我建议不翻译。

/cc @Jinjiang

2021-05-04 16:29 UTC, Justineo commented on src/api/options-composition.md
> +  `attrs` 和 `slots` 是内部组件实例上相应值的代理。这样可以确保它们即使在更新后也始终会显示最新值，以便我们可以对它们进行结构分解，而不必担心访问过时的引用：
```suggestion
  `attrs` 和 `slots` 是内部组件实例上相应值的代理。这样可以确保它们即使在更新后也始终会显示最新值，以便我们可以对它们进行解构，而不必担心访问过时的引用：
```

2021-05-04 16:29 UTC, Justineo commented on src/api/options-lifecycle-hooks.md
> +        /* 这将导致 renderTriggered 调用
```suggestion
        /* 这将导致 renderTriggered 被调用
```

2021-05-04 16:29 UTC, Justineo commented on src/community/join.md
> +## 你将享有的资源
这里几个标题里的“你”我觉得都可以移除

2021-05-04 16:29 UTC, Justineo commented on src/community/join.md
> +## 你可以参与的方式
```suggestion
## 参与方式
```

2021-05-04 16:29 UTC, Justineo commented on src/community/join.md
> +### 分享 (并积累) 你的经验
```suggestion
### 分享 (并积累) 经验
```

2021-05-04 16:29 UTC, Justineo commented on src/guide/composition-api-setup.md
> +注意，从 `setup` 返回的 [refs](../api/refs-api.html#ref) 在模板中访问时是 [shallow 自动解构](/guide/reactivity-fundamentals.html#ref-解开)的，因此不应在模板中使用 `.value`。
解包？

2021-05-04 16:29 UTC, Justineo commented on src/guide/contributing/writing-guide.md
> +- **使用牛津逗号** (；例如：“a，b，and c” 替换 “a，b and c”)。！[为什么牛津逗号很重要](/images/oxford-comma.jpg)
```suggestion
- **使用牛津逗号** (例如：用“a，b，and c”替换“a，b and c”)。[为什么牛津逗号很重要](/images/oxford-comma.jpg)
```

Ps. 这个图貌似不存在，需要上游修正

2021-05-04 16:29 UTC, Justineo commented on src/guide/installation.md
> +可能会出现这样的情况，当你的用户名中有一个空格，比如 'Mike Baker' 时，vite 就不能成功创建，可以尝试：
```suggestion
可能会出现这样的情况，当你的用户名中有一个空格，比如 'Mike Baker' 时， Vite 就不能成功创建，可以尝试：
```

2021-05-04 16:29 UTC, Justineo commented on src/guide/migration/events-api.md
> +但是可以使用实现事件 emitter 接口的外部库来替换的 eventHub 模式，例如 [mitt](https://github.com/developit/mitt) 或 [tiny-emitter](https://github.com/scottcorgan/tiny-emitter)。
这个 emitter 改成不翻译是什么原因呢？

2021-05-04 16:29 UTC, Justineo commented on src/guide/migration/introduction.md
> +- [单文件组件状态驱动的 CSS 变量 (`v-bind` in `<style>`)](https://github.com/vuejs/rfcs/blob/style-vars-2/active-rfcs/0000-sfc-style-variables.md) <Badge text="实验性" type="warning" />
```suggestion
- [单文件组件状态驱动的 CSS 变量 (`<style>` 中的 `v-bind`)](https://github.com/vuejs/rfcs/blob/style-vars-2/active-rfcs/0000-sfc-style-variables.md) <Badge text="实验性" type="warning" />
```

2021-05-04 16:29 UTC, Justineo commented on src/guide/migration/introduction.md
> +- [生命周期 `hook：` 事件前缀改为 `vnode-`](/guide/migration/vnode-lifecycle-events.html)
```suggestion
- [生命周期 `hook:` 事件前缀改为 `vnode-`](/guide/migration/vnode-lifecycle-events.html)
```

2021-05-04 16:29 UTC, Justineo commented on src/guide/migration/introduction.md
> +- [$on，$off 和 \$once 实例方法](/guide/migration/events-api.html)
```suggestion
- [$on、$off 和 $once 实例方法](/guide/migration/events-api.html)
```

2021-05-04 16:29 UTC, Justineo commented on src/guide/reactivity-fundamentals.md
> +当 ref 作为渲染上下文 (从 [setup()](composition-api-setup.html) 中返回的对象) 上的 property 返回并可以在模板中被访问时，它将自动浅层解构为内部值。只有嵌套的 ref 才会在模板中要求 `.value`：
ref unwrap 感觉需要统一一下，看了下目前已经用到的，有几个候选：
解包，展开，解开

/cc @veaba @Jinjiang

2021-05-04 16:29 UTC, Justineo commented on src/guide/reactivity.md
> +JavaScript 通常不是这样工作的，如果我们想用 JavaScript 编写类似的内容：
这里感觉破折号没什么问题

2021-05-04 16:29 UTC, Justineo commented on src/guide/reactivity.md
> +The use of Proxy does introduce a new caveat to be aware of: the proxied object is not equal to the original object in terms of identity comparison (`===`). For example:
已经翻译了，这里可能搞错了

2021-05-04 16:29 UTC, Justineo commented on src/guide/render-function.md
> +<!-- TODO: translation -->
这里翻译了

2021-05-04 16:29 UTC, Justineo commented on src/guide/render-function.md
> +`render` 函数通常只需要对[全局注册](/guide/component-registration.html#global-registration)的组件使用 `resolveComponent`。而[本地组件注册](/guide/component-registration.html#local-registration)却是可以跳过，请看下面的例子：
```suggestion
`render` 函数通常只需要对[全局注册](/guide/component-registration.html#global-registration)的组件使用 `resolveComponent`。而对于[局部注册](/guide/component-registration.html#local-registration)的却可以跳过，请看下面的例子：
```

2021-05-04 16:29 UTC, Justineo commented on src/guide/render-function.md
> +[`resolveDirective`](/api/global-api.html#resolvedirective) 是模板内部用来解析指令名称的同一个函数。只有当你还没有直接访问 directive 的定义对象时，才需要这样做。
```suggestion
[`resolveDirective`](/api/global-api.html#resolvedirective) 是模板内部用来解析指令名称的同一个函数。只有当你还没有直接访问指令的定义对象时，才需要这样做。
```

2021-05-04 21:19 UTC, veaba commented on src/guide/migration/events-api.md
> +但是可以使用实现事件 emitter 接口的外部库来替换的 eventHub 模式，例如 [mitt](https://github.com/developit/mitt) 或 [tiny-emitter](https://github.com/scottcorgan/tiny-emitter)。
找不到恰当的词汇表述，同时为了映射右侧 链接里的 tiny-emitter

2021-05-04 21:22 UTC, veaba commented on src/guide/reactivity.md
> +The use of Proxy does introduce a new caveat to be aware of: the proxied object is not equal to the original object in terms of identity comparison (`===`). For example:
```suggestion
Proxy 的使用确实引入了一个需要注意的新警告：在身份比较方面，被代理对象与原始对象不相等 (`===`)。例如:
```

2021-05-05 05:39 UTC, veaba commented on src/guide/reactivity.md
> +JavaScript 通常不是这样工作的，如果我们想用 JavaScript 编写类似的内容：
好的，恢复下，只要这个改动是来自 #347

2021-05-05 05:58 UTC, veaba commented on src/guide/contributing/writing-guide.md
> +- **使用牛津逗号** (；例如：“a，b，and c” 替换 “a，b and c”)。！[为什么牛津逗号很重要](/images/oxford-comma.jpg)
已修正，这里用了中文的感叹号了，图片没有显示出来了。

2021-05-13 12:33 UTC, Limiandy commented on src/api/global-api.md
> +允许在 [`setup`](/api/composition-api.html#setup) 的[单文件组件](/guide/single-file-component.html)函数中访问 CSS 模块。
这里我认为还是 翻译为 css 模块 比较好，同 react 一样，可以在 jsx 中像使用 js 模块中的属性一样，例如，demo css 文件中 有 .class 属性，可以在 jsx 中使用 demo[class] 绑定 className 属性。这么来年，更符合 模块的概念以及前端工程化、模块化的思想。

2021-05-13 13:01 UTC, Limiandy commented on src/api/basic-reactivity.md
> +与 [`reactive`](#reactive) 不同，任何使用 [`ref`](/api/refs-api.html#ref) 的 property 都**不会**被代理自动解构。
`As with reactive, if any property uses a ref it will be automatically unwrapped when it is accessed via the proxy:`, 这是原文吗？

2021-05-17 04:22 UTC, Justineo commented on src/api/global-api.md
> +允许在 [`setup`](/api/composition-api.html#setup) 的[单文件组件](/guide/single-file-component.html)函数中访问 CSS 模块。
CSS Modules 不是一个在 CSS spec 中的通用概念，他只是“模块”一个特定实现。当你说 CSS 模块，隐含的是 CSS 中有“模块”这个概念（比如 ES 模块），但是并没有。

2021-05-22 05:31 UTC, Jinjiang reviewed
除了 reactivity 和 render-function 其余页面均已经 review 过。谢谢

2021-05-22 05:31 UTC, Jinjiang commented on src/api/global-api.md
> +如果你使用的是 CDN 构建，那么全局 API 的功能可以通过全局 `Vue` 对象来访问，例如：
```suggestion
如果你使用的是 CDN 构建，那么全局 API 可以通过全局对象 `Vue` 来访问，例如：
```

2021-05-22 05:31 UTC, Jinjiang commented on src/api/global-api.md
> +处理响应性的全局函数，如 `reactive` 和 `ref`，是单独编写的。关于这些函数，请参见[响应性 API](/api/reactivity-api.html)。
```suggestion
处理响应性的全局函数，如 `reactive` 和 `ref`，其文档是单独编写的。关于这些函数，请参见[响应性 API](/api/reactivity-api.html)。
```

2021-05-22 05:31 UTC, Jinjiang commented on src/api/global-api.md
> +允许在 [`setup`](/api/composition-api.html#setup) 的[单文件组件](/guide/single-file-component.html)函数中访问 CSS 模块。
看上去这里不是特指 CSS Modules 这个名词，原文的 modules 也用了小写，而且感觉也没有要提及 CSS Modules 的具体概念的意思，所以这里我倾向于译为“CSS 模块”。

2021-05-22 05:31 UTC, Jinjiang commented on src/api/global-api.md
> +关于使用 CSS 模块的更多信息，请参阅 [Vue Loader - CSS 模块](https://vue-loader.vuejs.org/guide/css-modules.html)。
```suggestion
关于使用 CSS 模块的更多信息，请参阅 [Vue Loader - CSS Modules](https://vue-loader.vuejs.org/zh/guide/css-modules.html)。
```

2021-05-22 05:31 UTC, Jinjiang commented on src/api/global-api.md
> +接受一个参数: `name`
```suggestion
接受一个参数：`name`
```

2021-05-22 05:31 UTC, Jinjiang commented on src/api/options-assets.md
>  -  **参考**[自定义指令](../guide/custom-directive.html)
```suggestion
-  **参考：**[自定义指令](../guide/custom-directive.html)
```

2021-05-22 05:31 UTC, Jinjiang commented on src/guide/installation.md
> +可能会出现这样的情况，当你的用户名中有一个空格，比如 'Mike Baker' 时， Vite 就不能成功创建，可以尝试：
```suggestion
可能会出现这样的情况，当你的用户名中有一个空格，比如“Mike Baker”时，Vite 就不能成功创建。这时可以尝试：
```

2021-05-22 05:31 UTC, Jinjiang commented on src/guide/migration/events-api.md
> +但是可以使用实现事件 emitter 接口的外部库来替换的 eventHub 模式，例如 [mitt](https://github.com/developit/mitt) 或 [tiny-emitter](https://github.com/scottcorgan/tiny-emitter)。
```suggestion
但是该 eventHub 模式可以被替换为实现了事件触发器接口的外部库，例如 [mitt](https://github.com/developit/mitt) 或 [tiny-emitter](https://github.com/scottcorgan/tiny-emitter)。
```
个人觉得映射 tiny-emitter 的意义不大。

2021-05-22 05:31 UTC, Jinjiang commented on src/guide/migration/events-api.md
> +它提供了与 Vue 2 相同的事件 emitter API。
```suggestion
它提供了与 Vue 2 相同的事件触发器 API。
```

2021-05-22 05:31 UTC, Jinjiang commented on src/guide/migration/introduction.md
> +- 全局函数 `set` 和 `delete` 以及实例方法 `$set` 和 `$delete`。基于代理的变化检测不再需要它们。
```suggestion
- 全局函数 `set` 和 `delete` 以及实例方法 `$set` 和 `$delete`。基于代理的变化检测不再需要它们了。
```

2021-05-22 07:02 UTC, veaba commented
已 apply。

2021-05-22 16:55 UTC, Jinjiang commented on src/guide/contributing/translations.md
> +Vue 在全球被广泛使用，核心团队成员身处至少 6 个不同时区。社区一直在成长，我们希望让尽可能多的人能够获得文档。
```suggestion
Vue 在全球被广泛使用，核心团队成员身处多个不同时区。社区一直在成长，我们希望让尽可能多的人能够获得文档。
```

2021-05-22 16:55 UTC, Jinjiang commented on src/guide/contributing/translations.md
> +Vue 在全球被广泛使用，核心团队成员身处至少 6 个不同时区。社区一直在成长，我们希望让尽可能多的人能够获得文档。
"at least half a dozen"感觉是英文里一个模糊的讲法，对应到中文应该不会有人按照直译的方式来介绍团队，所以换了一个更通俗的讲法

2021-05-22 16:55 UTC, Jinjiang commented on src/guide/reactivity.md
> +1. **追踪当一个值被读取时**，例如，`val1 + val2` 读取了两个，即 `val1` 和 `val2`。
```suggestion
1. **当一个值被读取时进行追踪**，例如 `val1 + val2` 会同时读取 `val1` 和 `val2`。
```

2021-05-22 16:55 UTC, Jinjiang commented on src/guide/reactivity.md
> +2. **检测当某个改变时**，例如，当我们赋值 `val1 = 3`。
```suggestion
2. **当某个改变时进行检测**，例如，当我们赋值 `val1 = 3`。
```

2021-05-22 16:55 UTC, Jinjiang commented on src/guide/reactivity.md
>  proxy 对象对于用户来说是不可见的，但是在内部，它们使 Vue 能够在 property 的值被访问或修改的情况下进行依赖跟踪和变更通知。从 Vue 3 开始，我们的响应性现在可以在[独立的包](https://github.com/vuejs/vue-next/tree/master/packages/reactivity)中使用。需要注意的是，记录转换后的数据对象时，浏览器控制台输出的格
这一行应该原文也更新了：

> The proxied object is invisible to the user, but under the hood it enables Vue to perform dependency-tracking and change-notification when properties are accessed or modified. One caveat is that console logging will format proxied objects differently, so you may want to install [vue-devtools](https://github.com/vuejs/vue-devtools) for a more inspection-friendly interface.

2021-05-22 16:55 UTC, Jinjiang commented on src/guide/reactivity.md
> +Beyond a console log, we could do anything here we wish. We could even _not_ return the real value if we wanted to. This is what makes Proxies so powerful for creating APIs.
```suggestion
除了控制台日志，我们可以在这里做任何我们想做的事情。如果我们愿意，我们甚至可以不返回实际值。这就是为什么 Proxy 对于创建 API 如此强大。
```

这一行应该就是你之前删掉的 92 行

2021-05-22 16:55 UTC, Jinjiang commented on src/guide/reactivity.md
>  const dinner = {
原文 102 行应该更新为了
`get(target, property, receiver) {`

2021-05-22 16:55 UTC, Jinjiang commented on src/guide/reactivity.md
>  const dinner = {
原文113行应该是：

> The first step towards implementing reactivity with a Proxy is to track when a property is read. We do this in the handler, in a function called `track`, where we pass in the `target` and `property`:

2021-05-22 16:55 UTC, Jinjiang commented on src/guide/reactivity.md
>  const dinner = {
原文121-122行应该为：

```
  get(target, property, receiver) {
    track(target, property)
```

141-146 行也需要类似的更新

2021-05-22 16:55 UTC, Jinjiang commented on src/guide/reactivity.md
> +Proxy 的使用确实引入了一个需要注意的新警告：在身份比较方面，被代理对象与原始对象不相等 (`===`)。例如:
```suggestion
Proxy 的使用确实引入了一个需要注意的新警告：在身份比较方面，被代理对象与原始对象不相等 (`===`)。例如：
```

原本的标点符号是正确的

2021-05-22 16:55 UTC, Jinjiang commented on src/guide/reactivity.md
>  const obj = {}
原文197行和199行需要更新：

> Other operations that rely on strict equality comparisons can also be impacted, such as `.includes()` or `.indexOf()`.

> The best practice here is to never hold a reference to the original raw object and only work with the reactive version:

2021-05-22 16:55 UTC, Jinjiang commented on src/guide/reactivity.md
>  ## 侦听器
```suggestion
## 如何让渲染响应变化
```

`## How Rendering Reacts to Changes`

2021-05-22 16:55 UTC, Jinjiang commented on src/guide/render-function.md
> +如果没有 props ，那么通常可以将 children 作为第二个参数进行传递。在这种情况下，可以将 `null` 作为第二个参数传递，将 children 作为第三个参数。
```suggestion
如果没有 prop，那么通常可以将 children 作为第二个参数传入。如果会产生歧义，可以将 `null` 作为第二个参数传入，将 children 作为第三个参数传入。
```

2021-05-22 16:55 UTC, Jinjiang commented on src/guide/render-function.md
> +      .replace(/\W+/g, '-') // 用破折号替换非单词字符
```suggestion
      .replace(/\W+/g, '-') // 用短横线替换非单词字符
```

中文里的破折号一般指全角横线，而且是两个连在一起使用，不是这里的 dash

2021-05-22 16:55 UTC, Jinjiang commented on src/guide/render-function.md
> +      .replace(/(^-|-$)/g, '') // 删除前后破折号
```suggestion
      .replace(/(^-|-$)/g, '') // 删除前后短横线
```

2021-05-22 16:55 UTC, Jinjiang commented on src/guide/render-function.md
> +通常不需要这种程度的灵活性。仅需一个更直接的替代方案取代 `resolveDynamicComponent`。
```suggestion
通常这种程度的灵活性是不需要的。通常 `resolveDynamicComponent` 可以被换做一个更直接的替代方案。
```

2021-05-23 06:11 UTC, veaba commented on src/guide/reactivity.md
>  const dinner = {
> 原文 102 行应该更新为了
> `get(target, property, receiver) {`

应该是原英文的问题，需要先提 PR。

2021-05-23 06:16 UTC, veaba commented
我们最好先把 reactivity.md 翻译完成再 merge 到 master

2021-05-23 18:23 UTC, Jinjiang commented
@veaba 没问题，take your time。其它文件我这边都没有问题了

2021-05-29 05:16 UTC, veaba commented
@Jinjiang Hi，翻译了 reactivity 麻烦你 review 一下哈。

2021-05-29 08:47 UTC, Jinjiang reviewed
review 了前 100 行🙏

2021-05-29 08:47 UTC, Jinjiang commented on src/guide/reactivity.md
> +Vue 通过使用 *effect* 来跟踪当前正在运行的函数。副作用是一个围绕函数的包裹器，在函数被调用之前就启动跟踪。Vue 知道哪个副作用在何时运行，并能在需要时再次执行它。
```suggestion
Vue 通过一个*副作用 (effect)* 来跟踪当前正在运行的函数。副作用是一个函数的包裹器，在函数被调用之前就启动跟踪。Vue 知道哪个副作用在何时运行，并能在需要时再次执行它。
```

这里的 effect 因为上下文同时有中文描述和英文同名 API，所以用中文做描述，同时在括号里附带了英文。

2021-05-29 08:47 UTC, Jinjiang commented on src/guide/reactivity.md
> +为了更好地理解这一点，让我们尝试在没有 Vue 的情况下自己实现类似的东西，看看它可能如何工作。
```suggestion
为了更好地理解这一点，让我们尝试脱离 Vue 实现类似的东西，以看看它如何工作。
```

might 我这里没有翻译，感觉不影响理解。另外我看接下来还有类似的句子我看你也把 might 的含义忽略了，比如：“We might implement it something like this” 你翻译为了“我们的实现如下”。

我觉得应该没有问题

2021-05-29 08:47 UTC, Jinjiang commented on src/guide/reactivity.md
> +// 维持一个执行副作用的堆栈
```suggestion
// 维持一个执行副作用的栈
```

堆应该是 heap，栈是 stack

2021-05-29 08:47 UTC, Jinjiang commented on src/guide/reactivity.md
> +当我们的副作用被调用时，在调用 `fn` 之前，它会把自己推到 `runningEffects` 数组中。任何想知道当前正在运行的副作用的东西都可以检查这个数组。
```suggestion
当我们的副作用被调用时，在调用 `fn` 之前，它会把自己推到 `runningEffects` 数组中。这个数组可以用来检查当前正在运行的副作用。
```

anything A can do B 可以简译为：“B 可以用来做 A”

2021-05-29 08:47 UTC, Jinjiang commented on src/guide/reactivity.md
> +虽然 Vue 的公开 API 不包括任何直接创建副作用的方法，但它确实暴露了一个叫做 `watchEffect` 的函数，它的行为很像我们例子中的 `createEffect` 函数。我们会在[指南后面](/guide/reactivity-computed-watchers.html#watcheffect)详细讨论这个问题。
```suggestion
虽然 Vue 的公开 API 不包括任何直接创建副作用的方法，但它确实暴露了一个叫做 `watchEffect` 的函数，它的行为很像我们例子中的 `createEffect` 函数。我们会在[该指南后面的部分](/guide/reactivity-computed-watchers.html#watcheffect)详细讨论这个问题。
```

2021-05-29 08:47 UTC, Jinjiang commented on src/guide/reactivity.md
> +## Vue如何跟踪变化
```suggestion
## Vue 如何跟踪变化
```

2021-05-29 08:47 UTC, Jinjiang commented on src/guide/reactivity.md
> +当我们从一个组件的 `data` 函数中返回一个普通的 JavaScript 对象时，Vue 会将该对象包裹在一个带有 `get` 和 `set` 处理程序的 [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) 中。代理是在 ES6 中引入的，它使 Vue
```suggestion
当我们从一个组件的 `data` 函数中返回一个普通的 JavaScript 对象时，Vue 会将该对象包裹在一个带有 `get` 和 `set` 处理程序的 [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) 中。Proxy 是在 ES6 中引入的，它使 Vue 3 避免了 Vue 早期版本中存在的一些响应性问题。
```

2021-05-29 08:47 UTC, Jinjiang commented on src/guide/reactivity.md
> +那看起来灵敏，不过，需要一些[代理](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy)的知识才能理解! 所以让我们深入了解一下。有很多关于代理的文档，但你真正需要知道的是，**代理是一个封装另一个对象的对象，允许你拦截与该对象的任何交互。**
```suggestion
那看起来灵敏，不过，需要一些 [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) 的知识才能理解！所以让我们深入了解一下。有很多关于 Proxy 的文档，但你真正需要知道的是，**Proxy 是一个对象，它包装了另一个对象，并允许你拦截对该对象的任何交互。**
```

为“encase”回避了“封装 (encapsulate)”这样的专有译法

2021-05-29 08:47 UTC, Jinjiang commented on src/guide/reactivity.md
> +这里我们截获了读取目标对象 property 的举动。像这样的处理函数也称为 *trap*。有许多可用的不同类型陷阱，每个都处理不同类型的交互。
```suggestion
这里我们截获了读取目标对象 property 的举动。像这样的处理函数也称为一个*圈套 (trap)*。有许多可用的不同类型圈套，每个都处理不同类型的交互。
```

同上，这里用了中文加括号内的英文

@Justineo 这里的 trap 你有什么译法推荐？我个人觉得“圈套”比“陷阱”稍微合适一点，但也想听听你的意见。谢谢

2021-05-29 08:47 UTC, Jinjiang commented on src/guide/reactivity.md
> +使用代理的一个难点是 `this` 绑定。我们希望任何方法都绑定到代理，而不是目标对象，这样我们也可以拦截它们。值得庆幸的是，ES6 引入了另一个名为 `Reflect` 的新特性，它允许我们以最小的代价消除了这个问题：
```suggestion
使用 Proxy 的一个难点是 `this` 绑定。我们希望任何方法都绑定到这个 Proxy，而不是目标对象，这样我们也可以拦截它们。值得庆幸的是，ES6 引入了另一个名为 `Reflect` 的新特性，它允许我们以最小的代价消除了这个问题：
```

2021-05-29 08:47 UTC, Jinjiang commented on src/guide/reactivity.md
>  const dinner = {
[英文原版](https://github.com/vuejs/docs-next/compare/efbbe59...91a4425#diff-4d47e7364676bfe0411297303264e00087269482dd4665c4fc9b139dfae30fbcL102)
![image](https://user-images.githubusercontent.com/206848/120064041-f3a46300-c09c-11eb-804b-6f1621aa845a.png)

当前文件

![image](https://user-images.githubusercontent.com/206848/120064051-0159e880-c09d-11eb-9826-1a030ce1597f.png)

我理解这里只是个形参变化，谈不上是个问题，而且之前已经有一个地方我们改好了：

![image](https://user-images.githubusercontent.com/206848/120064097-37976800-c09d-11eb-9139-ea7d2920e6ec.png)

2021-05-29 08:47 UTC, Jinjiang commented on src/guide/reactivity.md
>  const dinner = {
哦，我明白你的意思了，我建议这里借这个机会一并同步到最新吧，因为这个文件改动比较大，我这里其实没办法“差量” review，只能全量 review。如果是原文有译法问题我会忽略，如果是有内容缺失我是比较难 review 的，希望可以理解。

2021-05-29 09:11 UTC, veaba commented
@Jinjiang  我怎么给感觉 proxy 的用法又混乱了呀~ 😂 

![image](https://user-images.githubusercontent.com/8652596/120064843-dd000b00-c0a0-11eb-81d4-7b5720239302.png)

2021-05-29 09:19 UTC, veaba commented
我将 reactivity.md 更新到最新吧。

2021-05-29 09:29 UTC, veaba commented on src/guide/reactivity.md
> +这里我们截获了读取目标对象 property 的举动。像这样的处理函数也称为 *trap*。有许多可用的不同类型陷阱，每个都处理不同类型的交互。
圈套的叫法挺不错。

2021-05-29 14:03 UTC, Justineo commented on src/guide/reactivity.md
> +这里我们截获了读取目标对象 property 的举动。像这样的处理函数也称为 *trap*。有许多可用的不同类型陷阱，每个都处理不同类型的交互。
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Proxy

MDN 上翻译成了“捕捉器”，我觉得更好一点？

2021-05-29 17:22 UTC, Jinjiang commented
> @Jinjiang 我怎么给感觉 proxy 的用法又混乱了呀~ 😂
> 
> ![image](https://user-images.githubusercontent.com/8652596/120064843-dd000b00-c0a0-11eb-81d4-7b5720239302.png)

我提出修改的地方应该都是特指 ES Proxy 所以应该保留英文

2021-05-29 17:26 UTC, Jinjiang commented on src/guide/reactivity.md
> +这里我们截获了读取目标对象 property 的举动。像这样的处理函数也称为 *trap*。有许多可用的不同类型陷阱，每个都处理不同类型的交互。
我没有个人偏好，如果大家都没有意见那我们统一到捕捉器好了

2021-05-29 17:42 UTC, Jinjiang reviewed
Review 了其余的部分

2021-05-29 17:42 UTC, Jinjiang commented on src/guide/reactivity.md
> +这里没有展示 `track` 的实现。它将检查当前运行的 *effect*，并将其记录在 `target` 和 `property` 旁边。这就是 Vue 如何知道 property 是副作用的依赖项。
```suggestion
这里没有展示 `track` 的实现。它将检查当前运行的*副作用*，并将其记录在 `target` 和 `property` 旁边。这就是 Vue 如何知道这个 property 是该副作用的依赖项。
```

2021-05-29 17:42 UTC, Jinjiang commented on src/guide/reactivity.md
> +最后，我们需要在 property 值更改时重新运行副作用。为此，我们需要在代理上使用一个 `set` 处理函数：
```suggestion
最后，我们需要在 property 值更改时重新运行这个副作用。为此，我们需要在代理上使用一个 `set` 处理函数：
```

2021-05-29 17:42 UTC, Jinjiang commented on src/guide/reactivity.md
> +- **读值时的跟踪**：proxy 的 `get` 处理函数中 `track` 函数记录了该 property 和当前副作用。
```suggestion
1. **读值时的跟踪**：proxy 的 `get` 处理函数中 `track` 函数记录了该 property 和当前副作用。
```

2021-05-29 17:42 UTC, Jinjiang commented on src/guide/reactivity.md
> +- **检测该值何时发生变化**：在 proxy 上调用 `set` 处理函数。
```suggestion
2. **检测该值何时发生变化**：在 proxy 上调用 `set` 处理函数。
```

2021-05-29 17:42 UTC, Jinjiang commented on src/guide/reactivity.md
> +- **触发函数以便它可以更新最终值**：`trigger` 函数查找哪些副作用依赖于该 property 和它们的执行。
```suggestion
3. **触发函数以便它可以更新最终值**：`trigger` 函数查找哪些副作用依赖于该 property 和它们的执行。
```

2021-05-29 17:42 UTC, Jinjiang commented on src/guide/reactivity.md
> +`data` 返回的对象将被包裹在响应式代理中，并存储为 `this.$data`。property `this.val1` 和 `this.val2` 分别是 `this.$data.val1` 和 `this.$data.val2` 的别名，因此它们通过相同的代理。
```suggestion
`data` 返回的对象将被包裹在响应式代理中，并存储为 `this.$data`。Property `this.val1` 和 `this.val2` 分别是 `this.$data.val1` 和 `this.$data.val2` 的别名，因此它们通过相同的代理。
```

2021-05-29 17:42 UTC, Jinjiang commented on src/guide/reactivity.md
> +### Proxy 对象
```suggestion
### 被代理的对象
```

2021-05-29 17:42 UTC, Jinjiang commented on src/guide/reactivity.md
> +当一个嵌套对象从一个响应式代理中被访问时，该对象在被返回之前也被转换为一个代理：
```suggestion
当从一个响应式代理中访问一个嵌套对象时，该对象在被返回之前*也*被转换为一个代理：
```

2021-05-29 17:42 UTC, Jinjiang commented on src/guide/reactivity.md
> +这里的最佳实践是永远不要维持有对原始对象的引用，而只使用响应式版本。
```suggestion
这里的最佳实践是永远不要持有对原始对象的引用，而只使用响应式版本。
```

2021-05-29 17:42 UTC, Jinjiang commented on src/guide/reactivity.md
> +一个组件的模板被编译成一个 [`render`](/guide/render-function.html) 函数。渲染函数创建 [VNodes](/guide/render-function.html#the-virtual-dom-tree)，描述该组件应该如何被渲染。它被包裹在一个副作用中，允许 Vue 在运行时跟踪被 “touch” 的 property。
```suggestion
一个组件的模板被编译成一个 [`render`](/guide/render-function.html) 函数。渲染函数创建 [VNodes](/guide/render-function.html#虚拟-dom-树)，描述该组件应该如何被渲染。它被包裹在一个副作用中，允许 Vue 在运行时跟踪被“触达”的 property。
```

2021-05-29 17:45 UTC, Jinjiang commented on src/guide/reactivity.md
> +proxy 对象对于用户来说是不可见的，但是在内部，它们使 Vue 能够在 property 的值被访问或修改的情况下进行依赖跟踪和变更通知。有一点需要注意，控制台日志会以不同的方式对 proxy 对象进行格式化，因此你可能需要安装 [vue-devtools](https://github.com/vuejs/vue-devtools)，以提供一种更易于检查的界面。
```suggestion
该被代理的对象对于用户来说是不可见的，但是在内部，它们使 Vue 能够在 property 的值被访问或修改的情况下进行依赖跟踪和变更通知。有一点需要注意，控制台日志会以不同的方式对 proxy 对象进行格式化，因此你可能需要安装 [vue-devtools](https://github.com/vuejs/vue-devtools)，以提供一种更易于检查的界面。
```

2021-05-30 04:53 UTC, Jinjiang approved these changes

2021-05-30 04:54 UTC, Jinjiang commented
@Justineo anything still need discussions?

2021-05-30 05:22 UTC, Jinjiang commented on src/guide/contributing/writing-guide.md
> +- **使用牛津逗号** (；例如：“a，b，and c” 替换 “a，b and c”)。![为什么牛津逗号很重要](/images/oxford-comma.jpg)
```suggestion
- **使用牛津逗号** (例如：“a，b，and c” 替换 “a，b and c”)。![为什么牛津逗号很重要](/images/oxford-comma.jpg)
```

2021-05-30 05:29 UTC, Jinjiang commented on src/guide/reactivity-fundamentals.md
> +当 ref 作为渲染上下文 (从 [setup()](composition-api-setup.html) 中返回的对象) 上的 property 返回并可以在模板中被访问时，它将自动浅层解构为内部值。只有嵌套的 ref 才会在模板中要求 `.value`：
unwrap 的译法可以单独处理，这里先算作 resolved

2021-05-30 05:31 UTC, Jinjiang commented on src/guide/composition-api-setup.md
> +注意，从 `setup` 返回的 [refs](../api/refs-api.html#ref) 在模板中访问时是 [shallow 自动解构](/guide/reactivity-fundamentals.html#ref-解开)的，因此不应在模板中使用 `.value`。
unwrap 的译法可以单独处理，这里先算作 resolved

2021-05-31 02:44 UTC, Justineo approved these changes

2021-05-31 03:37 UTC, merged