fix: delete original English
vuejs/docs-next-zh-cn pull request #45
Opened 2020-09-14 03:45 UTC by ajycc20

fix: plugins.md 删除源英文句子
fix: reactivity.md 将 proxy 更新为 Proxy
fix: reactivity-fundamentals.md 删除源英文句子，移除了一些多余的汉字
fix: reactivity-computed-wachers.md 修复超链接，移除TODOs，翻译未为翻译的句子

2020-09-14 09:16 UTC, veaba commented on src/guide/reactivity-computed-watchers.md
> +### 效果冲刷时间
可以暂时翻译为 “效果冲刷时间”，[wiki 存在争议的译法](https://github.com/vuejs/docs-next-zh-cn/wiki/%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A#%E5%AD%98%E5%9C%A8%E4%BA%89%E8%AE%AE%E7%9A%84%E8%AF%91%E6%B3%95)， 对于有争议的翻译术语可以发起 issue 进一步讨论。

2020-09-14 09:22 UTC, veaba requested changes

2020-09-14 09:22 UTC, veaba commented on src/guide/reactivity-computed-watchers.md
> +`watch` 与 [`watchEffect`](#watcheffect) 共享 [阻止侦听器](#阻止侦听器)，[副作用失效](#副作用失效) (改造将 `onInvalidate` 作为第三个参数传递给回调)、[效果冲洗时间](#效果冲洗时间) 和 [侦听器调试](#侦听器调试) 行为。
前面讨论：`effect-flush-timing` 暂翻 `效果冲刷时间`，这里需要更改下。

2020-09-14 09:26 UTC, ajycc20 commented on src/guide/reactivity-computed-watchers.md
> +### 效果冲刷时间
> 可以暂时翻译为 “效果冲刷时间”，[wiki 存在争议的译法](https://github.com/vuejs/docs-next-zh-cn/wiki/%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A#%E5%AD%98%E5%9C%A8%E4%BA%89%E8%AE%AE%E7%9A%84%E8%AF%91%E6%B3%95)， 对于有争议的翻译术语可以发起 issue 进一步讨论。

[关于 `Effect Flush Timing` 翻译问题](https://github.com/vuejs/docs-next-zh-cn/issues/48)

2020-09-14 09:29 UTC, ajycc20 commented on src/guide/reactivity-computed-watchers.md
> +`watch` 与 [`watchEffect`](#watcheffect) 共享 [阻止侦听器](#阻止侦听器)，[副作用失效](#副作用失效) (改造将 `onInvalidate` 作为第三个参数传递给回调)、[效果冲洗时间](#效果冲洗时间) 和 [侦听器调试](#侦听器调试) 行为。
> 前面讨论：`effect-flush-timing` 暂翻 `效果冲刷时间`，这里需要更改下。

已修改

2020-09-14 09:30 UTC, merged

2020-09-15 00:53 UTC, vspirit803 commented
composition api里面的翻译是"副作用刷新时机",是不是更通顺一点

2020-09-15 01:02 UTC, veaba commented
> composition api里面的翻译是"副作用刷新时机",是不是更通顺一点

可以在 #48  讨论