docs: 修复了一些组合式 API 中奇怪的翻译
vuejs/docs-next-zh-cn pull request #492
Opened 2021-05-10 07:07 UTC by renmu123

因没有在术语表中查到，遵循原来的翻译： `Composition API ` 翻译为 ` 组合式 API`，`Options API` 翻译为 `选项式 API`

2021-05-10 16:31 UTC, veaba commented on src/guide/composition-api-setup.md
> +`attrs` 和 `slots` 是有状态的对象，它们总是会随组件本身的更新而更新。这意味着你应该避免对它们进行解构，并始终以 `attrs.x` 或 `slots.x` 的方式引用 property。请注意，与 `props` 不同，`attrs` 和 ` slots` 是**非**响应式的。如果你打算依赖 `attrs` 或 `slots` 更改带来的副作用，那么应该在 `onUpdate
> 如果你打算依赖 `attrs` 或 `slots` 更改带来的副作用

这个句式，`带来`的副作用，这里很奇怪。

/cc @Justineo 看看这个

2021-05-10 23:45 UTC, renmu123 commented on src/guide/composition-api-setup.md
> +`attrs` 和 `slots` 是有状态的对象，它们总是会随组件本身的更新而更新。这意味着你应该避免对它们进行解构，并始终以 `attrs.x` 或 `slots.x` 的方式引用 property。请注意，与 `props` 不同，`attrs` 和 ` slots` 是**非**响应式的。如果你打算依赖 `attrs` 或 `slots` 更改带来的副作用，那么应该在 `onUpdate
我也觉得非常奇怪，但是想不到更好的翻译了

2021-05-12 14:50 UTC, watonyweng commented on src/guide/composition-api-setup.md
> +`attrs` 和 `slots` 是有状态的对象，它们总是会随组件本身的更新而更新。这意味着你应该避免对它们进行解构，并始终以 `attrs.x` 或 `slots.x` 的方式引用 property。请注意，与 `props` 不同，`attrs` 和 ` slots` 是**非**响应式的。如果你打算依赖 `attrs` 或 `slots` 更改带来的副作用，那么应该在 `onUpdate
如果你有基于  `attrs`  或  `slots`  的变更

2021-05-13 05:43 UTC, Limiandy commented on src/guide/composition-api-setup.md
> +`attrs` 和 `slots` 是有状态的对象，它们总是会随组件本身的更新而更新。这意味着你应该避免对它们进行解构，并始终以 `attrs.x` 或 `slots.x` 的方式引用 property。请注意，与 `props` 不同，`attrs` 和 ` slots` 是**非**响应式的。如果你打算依赖 `attrs` 或 `slots` 更改带来的副作用，那么应该在 `onUpdate
`如果你有基于 attrs 或 slots 的变更`， 这么翻译，我感觉很好

2021-05-13 06:30 UTC, renmu123 commented on src/guide/composition-api-setup.md
> +`attrs` 和 `slots` 是有状态的对象，它们总是会随组件本身的更新而更新。这意味着你应该避免对它们进行解构，并始终以 `attrs.x` 或 `slots.x` 的方式引用 property。请注意，与 `props` 不同，`attrs` 和 ` slots` 是**非**响应式的。如果你打算依赖 `attrs` 或 `slots` 更改带来的副作用，那么应该在 `onUpdate
我觉得这个翻译ok @veaba

2021-05-13 08:59 UTC, renmu123 commented on src/guide/composition-api-template-refs.md
> +但与生命周期钩子的一个关键区别是，`watch()` 和 `watchEffect()` 是在 DOM 被挂载或更新*之前*运行的，所以当侦听器运行时，模板引用还未被更新。
大家可以讨论一下 run effect 应该如何翻译，这个章节中都将其翻译为“副作用”， 我认为是有问题的。本章中关于这个单词有不少奇怪的翻译，我还没有对其进行修改

2021-05-13 14:56 UTC, veaba commented on src/guide/composition-api-template-refs.md
> +但与生命周期钩子的一个关键区别是，`watch()` 和 `watchEffect()` 是在 DOM 被挂载或更新*之前*运行的，所以当侦听器运行时，模板引用还未被更新。
`effect` 被翻译为 `副作用`

2021-05-14 07:33 UTC, renmu123 commented on src/guide/composition-api-template-refs.md
> +但与生命周期钩子的一个关键区别是，`watch()` 和 `watchEffect()` 是在 DOM 被挂载或更新*之前*运行的，所以当侦听器运行时，模板引用还未被更新。
`run the effect` 应该作何翻译，我觉得翻译成 `运行副作用` 比较奇怪。

2021-05-16 03:30 UTC, watonyweng commented on src/guide/composition-api-template-refs.md
> +但与生命周期钩子的一个关键区别是，`watch()` 和 `watchEffect()` 是在 DOM 被挂载或更新*之前*运行的，所以当侦听器运行时，模板引用还未被更新。
`watch()` 和 `watchEffect()` 产生副作用是在 DOM 被挂载或更新*之前*运行的，所以当侦听器运行时，模板引用还未被更新。

2021-05-18 01:56 UTC, renmu123 commented on src/guide/composition-api-template-refs.md
> +但与生命周期钩子的一个关键区别是，`watch()` 和 `watchEffect()` 是在 DOM 被挂载或更新*之前*运行的，所以当侦听器运行时，模板引用还未被更新。
`watch()` 和 `watchEffect()` 是在 DOM 被挂载或更新之前运行并产生副作用的，所以当侦听器运行时，模板引用还未被更新。

我还是觉得翻译成成`产生副作用`有点奇怪，翻译成`产生效果`怎么样

2021-05-18 04:03 UTC, renmu123 commented on src/guide/composition-api-introduction.md
> +新的 `setup` 组件选项在创建组件**之前**执行，一旦 `props` 被解析，就作为组合式 API 的入口点。
后半句话有生命好的翻译吗？
> The new setup component option is executed before the component is created, once the props are resolved, and serves as the entry point for composition API's.

2021-05-22 02:15 UTC, watonyweng commented on src/guide/composition-api-introduction.md
> +新的 `setup` 组件选项在创建组件**之前**执行，一旦 `props` 被解析，就作为组合式 API 的入口点。
新的 `setup` 组件选项在创建组件**之前**执行，一旦 `props` 被解析，它就是组合式 API 的入口点。

2021-05-22 06:54 UTC, veaba commented on src/guide/composition-api-template-refs.md
> +但与生命周期钩子的一个关键区别是，`watch()` 和 `watchEffect()` 是在 DOM 被挂载或更新*之前*运行的，所以当侦听器运行时，模板引用还未被更新。
effect 译为副作用是为了沿袭 composition-api 文档的习惯，尽管本身中译后的含义稍微有些奇怪。

如有进一步译法可以发起 issue 讨论。

/cc @Jinjiang @Justineo

2021-05-27 01:43 UTC, renmu123 commented on src/guide/composition-api-provide-inject.md
> +在 `setup()` 中使用 `inject` 时，也需要从 `vue` 显式导入。一旦我们这样做了，我们就可以调用它来定义如何将它暴露给我们的组件。
这句话有什么更好的翻译吗？
> 一旦我们这样做了，我们就可以调用它来定义如何将它暴露给我们的组件。

原文：
> When using inject in setup(), we also need to explicitly import it from vue. Once we do so, this allows us to invoke it to define how we want to expose it to our component.

2021-05-30 07:41 UTC, watonyweng commented on src/guide/composition-api-provide-inject.md
> +在 `setup()` 中使用 `inject` 时，也需要从 `vue` 显式导入。一旦我们这样做了，我们就可以调用它来定义如何将它暴露给我们的组件。
一旦我们这样做了，就可以使用它来导出我们想要定义的组件。

2021-06-01 03:33 UTC, zjfresh commented on src/guide/composition-api-provide-inject.md
> +在 `setup()` 中使用 `inject` 时，也需要从 `vue` 显式导入。一旦我们这样做了，我们就可以调用它来定义如何将它暴露给我们的组件。
当这样做了后，这让我们可以调用它去阐明我们想要怎样暴露它给我们组件。

2021-06-01 09:29 UTC, Justineo requested changes

2021-06-01 09:29 UTC, Justineo commented on src/guide/composition-api-setup.md
> +`attrs` 和 `slots` 是有状态的对象，它们总是会随组件本身的更新而更新。这意味着你应该避免对它们进行解构，并始终以 `attrs.x` 或 `slots.x` 的方式引用 property。请注意，与 `props` 不同，`attrs` 和 `slots` 是**非**响应式的。如果你有基于 attrs 或 slots 的变更，那么应该在 `onUpdated` 生命周期钩子中执
原来的翻译更准确一些。

2021-06-01 09:29 UTC, Justineo commented on src/guide/composition-api-setup.md
> +如果 `setup` 返回一个对象，就可以像 `props` properties 传递给 `setup` 一样，在组件的模板中访问该对象的 property：
```suggestion
如果 `setup` 返回一个对象，那么该对象的 property 以及传递给 `setup` 的 `props` 参数中的 property 就都可以在模板中访问到：
```

2021-06-01 09:29 UTC, Justineo commented on src/guide/composition-api-template-refs.md
> +但与生命周期钩子的一个关键区别是，`watch()` 和 `watchEffect()` 是在 DOM 被挂载或更新*之前*运行的，所以当侦听器运行时，模板引用还未被更新。
这样翻译的意思是不对的，effect 是 `watch`/`watchEffect` 的参数，这里面说的是参数的执行时机，不是 `watch`/`watchEffect` 的执行时机。

```suggestion
但与生命周期钩子的一个关键区别是，`watch()` 和 `watchEffect()` 在 DOM 挂载或更新*之前*运行副作用，所以当侦听器运行时，模板引用还未被更新。
```

2021-06-04 14:38 UTC, veaba commented on src/guide/composition-api-provide-inject.md
> +1. name
```suggestion
1. 要 inject 的 property 的 name
```

2021-06-04 14:54 UTC, merged