docs: update reactive translation
vuejs/docs-next-zh-cn pull request #52
Opened 2020-09-15 07:33 UTC by veaba

- 全局纠正 响应式 翻译

2020-09-15 07:40 UTC, Justineo requested changes

2020-09-15 07:40 UTC, Justineo commented on src/api/options-composition.md
> +  `setup` 还可以返回一个 render 函数，该函数可以直接使用在同一作用域中声明的响应式状态：
```suggestion
  `setup` 还可以返回一个渲染函数，该函数可以直接使用在同一作用域中声明的响应式状态：
```

2020-09-15 07:40 UTC, Justineo commented on src/guide/component-edge-cases.md
> +感谢 Vue 的响应式系统，它总是知道什么时候更新 (如果你使用正确的话)。但是，在某些边缘情况下，你可能希望强制更新，尽管事实上没有任何响应式数据发生更改。还有一些情况下，你可能希望防止不必要的更新。
```suggestion
得益于其响应式系统，Vue 总是知道何时更新 (如果你使用正确的话)。但是，在某些边缘情况下，你可能希望强制更新，尽管事实上没有任何响应式数据发生更改。还有一些情况下，你可能希望防止不必要的更新。
```

2020-09-15 07:40 UTC, Justineo commented on src/guide/component-provide-inject.md
>  ## 与响应式一起工作
我在想，reactive 译为“响应式”的话，reactivity 是不是翻译为“响应性”更好？

@veaba @Jinjiang

2020-09-15 07:40 UTC, Justineo commented on src/guide/composition-api-setup.md
> +但是，因为 `props` 是响应性的，你不能**使用 ES6 解构**，因为它会消除 prop 的响应式。
同上

2020-09-15 08:07 UTC, veaba commented on src/guide/component-provide-inject.md
>  ## 与响应式一起工作
> 我在想，reactive 译为“响应式”的话，reactivity 是不是翻译为“响应性”更好？
> 
> @veaba @Jinjiang

你这么一说，我自己都糊涂了，:joy:  `响应式` 和 `响应性` 分不清。

我摘了英文版 实际例子来对比下。

|例子|代入翻译|
|----|----|
|reactive proxy |响应式prop|
|reactive state |响应式状态|
|reactive property|响应式 property||
|reactivity tracking|响应性追踪|
|losing reactivity|丢失响应性|
|reactivity system|响应性系统|

好像也说的过去，`响应式` 换成 `响应性`可以，但反过来，似乎不是很顺。

2020-09-16 21:14 UTC, veaba commented on src/guide/composition-api-setup.md
> +但是，因为 `props` 是响应性的，你不能**使用 ES6 解构**，因为它会消除 prop 的响应式。
@Justineo  如 #53 讨论的，形容词reactive 用响应式，名词reactivity用响应性

2020-09-16 21:23 UTC, closed without merging

2020-09-16 21:23 UTC, veaba commented
该  PR 需要重新处理。