Sync #4aec4e4
vuejs/docs-next-zh-cn pull request #533
Opened 2021-05-31 03:50 UTC by Jinjiang

## Description of Problem

The diff of the original update: https://github.com/vuejs/docs-next/compare/91a4425...4aec4e4

And I list all the rest translation to do:
- `api/application-api.md`
- `api/built-in-components.md`
- `api/composition-api.md`
- `api/global-api.md`
- `guide/installation`
- `guide/render-function`
- `guide/ssr`
- `guide/transitions-list`
- `guide/typescript-support`
- `guide/migration/async-components`
- `guide/migration/custom-directives`
- `guide/migration/emits-option`
- `guide/migration/transition-as-root`
- `guide/migration/transition-group`
- `guide/migration/transision`
- `guide/ssr/build-config`
- `guide/ssr/getting-started`
- `guide/ssr/hydration`
- `guide/ssr/introduction`
- `guide/ssr/routing`
- `guide/ssr/server`
- `guide/ssr/structure`
- `guide/ssr/universal`
- `cookbook/automatic-global-registration-of-base-components.md`

## Proposed Solution

## Additional Information

Thanks.

2021-05-31 17:17 UTC, veaba commented on src/guide/installation.md
> +在用 Vue 构建大型应用时推荐使用 npm 安装<sup>[[1]](#footnote-1)</sup> 。NPM 能很好地和诸如 [Webpack](https://webpack.js.org/) 或 [Rollup](https://rollupjs.org/) 模块打包器配合使用。
```suggestion
在用 Vue 构建大型应用时推荐使用 npm 安装<sup>[[1]](#footnote-1)</sup> 。NPM 能很好地和诸如 [webpack](https://webpack.js.org/) 或 [Rollup](https://rollupjs.org/) 模块打包器配合使用。
```

2021-05-31 17:18 UTC, veaba commented on src/guide/installation.md
> +在用 Vue 构建大型应用时推荐使用 npm 安装<sup>[[1]](#footnote-1)</sup> 。NPM 能很好地和诸如 [Webpack](https://webpack.js.org/) 或 [Rollup](https://rollupjs.org/) 模块打包器配合使用。
英文稳定 `Webpack` 又改回小写了。

2021-05-31 17:22 UTC, veaba commented on src/guide/migration/custom-elements-interop.md
> +- **非兼容**：检测并确定哪些标签应该被视为自定义元素的过程现在会在模板编译期间执行，且应该通过编译器选项而不是运行时配置来配置。
```suggestion
- **非兼容**：检测并确定哪些标签应该被视为自定义元素的过程，现在会在模板编译期间执行，且应该通过编译器选项而不是运行时配置来配置。
```

2021-05-31 17:34 UTC, veaba commented
同步的内容+范围已校对没问题，这一分支，先消灭小块的 TODO。

2021-06-02 01:46 UTC, Justineo requested changes

2021-06-02 02:10 UTC, Jinjiang commented
> 同步的内容+范围已校对没问题，这一分支，先消灭小块的 TODO。

是的，这边大块的翻译我都没有做，这样整个 PR 的进程会快一些，也避免大段翻译讨论出现在 sync 的 PR 里

2021-06-02 08:56 UTC, Justineo approved these changes

2021-06-02 08:57 UTC, Justineo approved these changes

2021-06-02 09:13 UTC, merged