docs: Fix translations error in migration/global-api-treeshaking.md
vuejs/docs-next-zh-cn pull request #535
Opened 2021-06-01 08:19 UTC by zjfresh

## Description of Problem
修复该页面中的中文翻译不通顺问题
## Proposed Solution

## Additional Information

2021-06-01 10:20 UTC, Justineo requested changes

2021-06-01 10:20 UTC, Justineo commented on src/guide/migration/global-api-treeshaking.md
> +或者，如果你在对涉及 [async components](/guide/component-dynamic-async.html) 的应用程序进行单元测试，那么很可能你编写了以下内容：
```suggestion
或者，如果你在对涉及[异步组件](/guide/component-dynamic-async.html)的应用程序进行单元测试，那么很可能你编写了以下内容：
```

2021-06-01 10:20 UTC, Justineo commented on src/guide/migration/global-api-treeshaking.md
> +如 [webpack](https://webpack.js.org/) 这样的模块打包工具支持 [tree-shaking](https://webpack.js.org/guides/tree-shaking/)，这是“死代码消除”的一个设想术语。遗憾的是，由于在之前的 Vue 版本中代码是这样编写的，全局 API 如 `Vue.nextTick()` 是非 tree-shakeable 的
```suggestion
如 [webpack](https://webpack.js.org/) 这样的模块打包工具支持 [tree-shaking](https://webpack.js.org/guides/tree-shaking/)，这是表达“死代码消除”的一个花哨术语。遗憾的是，由于在之前的 Vue 版本中代码是这样编写的，全局 API 如 `Vue.nextTick()` 是不支持 tree-shake 的，不管它们实际是否被使用，都会被包含在最终的打包产物中。
```

2021-06-01 10:20 UTC, Justineo commented on src/guide/migration/global-api-treeshaking.md
> +通过这一更改，如果模块打包工具支持 tree-shaking，则 Vue 应用程序中未使用的全局 API 将从最终的 bundle 中消除，从而获得最佳的文件大小。
```suggestion
通过这一更改，如果模块打包工具支持 tree-shake，则 Vue 应用程序中未使用的全局 API 将从最终的打包产物中排除，从而获得最佳的文件大小。
```

2021-06-01 10:20 UTC, Justineo commented on src/guide/migration/global-api-treeshaking.md
> +使用了全局 tree-shaking 后，用户只需为他们实际使用的功能“付费”，更好的是，知道了可选特性不会增加未使用它们的应用程序的 bundle 大小，以后框架大小就不再是追加核心功能的考虑因素了，如果有的话。
```suggestion
有了全局 tree-shake 后，用户只需为他们实际使用的功能“买单”。更好的是，知道了可选特性不会增加未使用它们的应用程序的打包产物大小，以后在追加核心功能时，即使对框架大小有顾虑，这也不再是那么重要的考虑因素了。
```

if at all 意思是，if we have a concern for the framework size at all

2021-06-01 10:20 UTC, Justineo commented on src/guide/migration/global-api-treeshaking.md
> +这将告诉 webpack 将 Vue 模块视为一个外部库，而不是输出打包它。
```suggestion
这将告诉 webpack 将 Vue 模块视为一个外部库，而不将它打包进来。
```

2021-06-01 10:20 UTC, Justineo commented on src/guide/migration/global-api-treeshaking.md
> +如果你选择的模块打包工具恰好是 [Rollup](https://rollupjs.org/)，你基本上可以直接获得相同的效果，因为默认情况下，Rollup 会将绝对模块 id (在我们的例子中为 `'vue'`) 作为外部依赖项，而不会将它们包含在最终的 bundle 中。但是在输出打包期间，它可能会抛出一个[“将 vue 作为外部依赖”](https://rollupjs.org/guide
```suggestion
如果你选择的模块打包工具恰好是 [Rollup](https://rollupjs.org/)，你基本上可以直接获得相同的效果。因为默认情况下，Rollup 会将绝对模块 id (在我们的例子中为 `'vue'`) 作为外部依赖项，而不会将它们包含在最终的 bundle 中。但是在输出打包期间，它可能会抛出一个[“将 vue 作为外部依赖”](https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency)警告，可使用 `external` 选项阻止该警告：
```

2021-06-02 15:59 UTC, veaba commented on src/guide/migration/global-api-treeshaking.md
> +通过这一更改，如果模块打包工具支持 tree-shake，则 Vue 应用程序中未使用的全局 API 将从最终的打包产物中排除，从而获得最佳的文件大小。
```suggestion
通过这一更改，如果模块打包工具支持 tree-shaking，则 Vue 应用程序中未使用的全局 API 将从最终的打包产物中排除，从而获得最佳的文件大小。
```

2021-06-02 15:59 UTC, veaba commented on src/guide/migration/global-api-treeshaking.md
> +通过这一更改，如果模块打包工具支持 tree-shake，则 Vue 应用程序中未使用的全局 API 将从最终的打包产物中排除，从而获得最佳的文件大小。
一般是保留原词的。

2021-06-02 16:27 UTC, Justineo commented on src/guide/migration/global-api-treeshaking.md
> +通过这一更改，如果模块打包工具支持 tree-shake，则 Vue 应用程序中未使用的全局 API 将从最终的打包产物中排除，从而获得最佳的文件大小。
我理解翻译以后一般不保留时态、复数等变形的，因为汉语里面不会根据这些去理解英文概念的意思。

2021-06-02 16:56 UTC, veaba reviewed
我想表述的是，中文里它更像是用以 `tree-shaking` 形式作为一个通用的叫法，表现的是一种技术术语。

2021-06-05 04:27 UTC, veaba commented
由于此 PR，仅还有 `tree-shaking` 存在一些疑问之外，目前已独立到 issue #548 讨论，现在可以合并了。

感谢各位。

2021-06-05 04:27 UTC, merged