Translated all rest migration docs
vuejs/docs-next-zh-cn pull request #551
Opened 2021-06-06 02:16 UTC by Jinjiang

## Description of Problem

- `/guide/migration/suspense`
- `/guide/migration/vnode-lifecycle-events`
- `/guide/migration/props-data`
- `/guide/migration/mount-changes`
- `/guide/migration/emits-option`

## Proposed Solution

## Additional Information

2021-06-07 09:13 UTC, renmu123 commented on src/guide/migration/suspense.md
> +组件在被正确渲染之前需要进行一些异步请求，是很常见的事情。组件通常会在本地处理这种逻辑，绝大多数情况下这是非常完美的做法。
在正确渲染组件之前进行一些异步请求是很常见的事。

2021-06-15 14:58 UTC, veaba commented on src/guide/migration/emits-option.md
> +这里高度推荐把使用 `emits` 的每个组件的所有的事件整理成文档。
这里的翻译是不是有点问题了，为啥要整理成为文档。

参考下：

> 强烈建议你使用 `emits' 来记录你的每个组件所发出的所有事件。

@Justineo 可以看看~~

2021-06-15 15:09 UTC, veaba requested changes

2021-06-15 15:09 UTC, veaba commented on src/guide/migration/suspense.md
> +    // 它阴性地包裹在一个 Promise 内
```suggestion
    // 它隐性地包裹在一个 Promise 内
```

2021-06-15 15:09 UTC, veaba commented
本 PR 完成 review~

2021-06-15 17:15 UTC, Jinjiang commented on src/guide/migration/emits-option.md
> +这里高度推荐把使用 `emits` 的每个组件的所有的事件整理成文档。
你的理解是对的，我来改一下

2021-06-16 02:24 UTC, merged