docs: re-translate style-guide
vuejs/docs-next-zh-cn pull request #621
Opened 2021-08-06 02:46 UTC by wxsms

见 #618 

这篇文章翻译质量略低，并且存在不少翻译错误，对它进行了重新翻译。目的是：

1. 修正翻译错误，如原文 `so learn and abide by them at all costs`，译文 `所以学习并接受它们带来的全部代价吧` -> `所以无论如何，学习并遵守它们吧`
2. 某些地方句子太长，增加标点符号，使文章阅读起来更轻松。如  `有些 Vue 特性的存在是为了照顾极端情况或帮助老代码的平稳迁移` -> `某些 Vue 特性的存在是为了照顾极端情况，或帮助老代码的平稳迁移`
3. 某些句式调整，使之更符合中文习惯。如 `如果在工程中使用 Vue，为了回避错误、小纠结和反模式，该指南是份不错的参考` -> `如果你在工程中使用了 Vue，本文是回避错误、小纠结和反模式的不错的参考`

当然我个人的能力是有限的，某些翻译可能我也没有做好，请大家多多指正！

2021-08-08 09:29 UTC, wxsms commented
@Jinjiang @veaba 已完成了，有空时请过目一下。优化的过程中与目前的英文版进行了校对，发现了不少翻译错误。

2021-08-11 06:17 UTC, renmu123 commented on src/style-guide/README.md
> +**使用模块作用域来确保外部无法访问到私有函数。如果无法做到这一点，就始终为插件、mixin 等不考虑作为对外公开 API 的自定义私有 property 使用 `$_` 前缀。并附带一个命名空间，以回避和其它作者的冲突 (比如 `$_yourPluginName_`)。**
就始终该为插件、mixin 等不考虑对外公开 API 的自定义私有 property 使用 `$_` 前缀。

2021-08-11 07:38 UTC, wxsms commented on src/style-guide/README.md
> +本文是官方的 Vue 特有代码风格指南。如果你在工程中使用了 Vue，本文可以帮助你回避错误和反模式，减少对细枝末节的过度纠结。不过，我们也不确信，对于所有的团队或工程来说，风格指南的所有内容都是理想的。因此，根据过去的经验、周边的技术栈或个人价值观来做出谨慎的偏差是可取的。
这句话我也觉得有点不通顺，但也是没有想到好的。

2021-08-11 07:45 UTC, Justineo requested changes

2021-08-11 07:45 UTC, Justineo commented on src/style-guide/README.md
> +本文是官方的 Vue 特有代码风格指南。如果你在工程中使用了 Vue，本文可以帮助你回避错误和反模式，减少对细枝末节的过度纠结。不过，我们也不确信，对于所有的团队或工程来说，风格指南的所有内容都是理想的。因此，根据过去的经验、周边的技术栈或个人价值观来做出谨慎的偏差是可取的。
```suggestion
本文是针对 Vue 代码的官方风格指南。如果你在工程中使用了 Vue，本文可以帮助你回避错误和反模式，减少对细枝末节的过度纠结。不过，我们认为任何风格指南都不会完美适用于所有的团队或项目。因此，我们也建议您根据过去的经验、周边的技术栈或个人价值观来做出有意识的调整。
```

2021-08-11 07:50 UTC, wxsms commented on src/style-guide/README.md
> +本文是官方的 Vue 特有代码风格指南。如果你在工程中使用了 Vue，本文可以帮助你回避错误和反模式，减少对细枝末节的过度纠结。不过，我们也不确信，对于所有的团队或工程来说，风格指南的所有内容都是理想的。因此，根据过去的经验、周边的技术栈或个人价值观来做出谨慎的偏差是可取的。
@Justineo 的建议挺好的，读起来更舒服。

2021-08-16 11:12 UTC, Justineo requested changes

2021-08-16 11:12 UTC, Justineo commented on src/style-guide/README.md
> +2. **列表渲染** (创建相同元素的多个变化)
```suggestion
2. **列表渲染** (创建相同元素的多个变体)
```

2021-08-16 11:12 UTC, Justineo commented on src/style-guide/README.md
> +6. **唯一的 Attribute** (需要唯一值的 attribute)
我在想这里是不是应该翻译成“唯一性”，唯一的 attribute 听起来表达的是没有其他 attribute。

2021-08-16 11:12 UTC, Justineo commented on src/style-guide/README.md
> +8. **其他 Attribute** (所有普通的，绑定或未绑定的 attribute)
```suggestion
8. **其他 Attribute** (所有普通的、绑定或未绑定的 attribute)
```

2021-08-16 11:12 UTC, Justineo commented on src/style-guide/README.md
> +      required: true
```suggestion
    required: true
```

2021-08-16 11:12 UTC, Justineo commented on src/style-guide/README.md
> +  default: false
```suggestion
    default: false
```

2021-08-16 11:12 UTC, Justineo commented on src/style-guide/README.md
> +    icon: String
```suggestion
  icon: String
```

2021-08-16 13:22 UTC, wxsms commented on src/style-guide/README.md
> +这样做可以跟现有的，以及未来的 HTML 元素[避免冲突](https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name)，因为所有的 HTML 元素名称都是单个单词的。
可以加一个“与”，避免与...产生冲突，好像好一些？

```suggestion
这样做可以避免与现有以及未来的 HTML 元素[产生冲突](https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name)，因为所有的 HTML 元素名称都是单个单词的。
```

2021-08-16 13:29 UTC, wxsms commented on src/style-guide/README.md
> +**Prop 定义应该尽量详细**
确实好像原来的翻译没什么问题。我改回去吧。

```suggestion
**Prop 定义应尽量详细**
```

2021-08-16 13:33 UTC, wxsms commented on src/style-guide/README.md
> +在 JavaScript 中，用多行分隔对象的多个 property 是很常见的最佳实践，因为这样更易读。模板和 [JSX](../guide/render-function.html#jsx) 同样值得考虑。
确实。对比起来，“同样值得考虑”读起来不太对劲。

2021-08-16 13:35 UTC, wxsms commented on src/style-guide/README.md
> +  小的，且更专注的计算属性减少了对信息将如何被使用的猜测，因此当需求变更时，重构的工作量也将更小。
感觉这里加一个“所作出”好一点。...对...所作出的假设更少。

```suggestion
  小且专注的计算属性对信息将如何被使用所作出的假设更少，因此当需求变更时，重构的工作量也将更小。
```

2021-08-16 13:37 UTC, wxsms commented on src/style-guide/README.md
> +在 HTML 中不带空格的 attribute 的值是可以没有引号的，这种实践通常导致*避免*空格，从而使得 attribute 的可读性变差。
👍

2021-08-16 13:42 UTC, wxsms commented on src/style-guide/README.md
> +这是我们为组件选项推荐的默认顺序。它们被划分为几大类，你能够由此知道新的 property 应该被放到哪里。
> This is the default order we recommend for component options. They're split into categories, so you'll know where to add new properties from plugins.

这里的 ‘plugin’ 感觉确实是有些难以理解，貌似没有这个词好像还更顺一些，所以就去掉了 😆

2021-08-16 13:46 UTC, wxsms commented on src/style-guide/README.md
> +6. **唯一的 Attribute** (需要唯一值的 attribute)
赞同，我把它改过来吧。

```suggestion
6. **唯一性 Attribute** (需要唯一值的 attribute)
```

2021-08-16 14:00 UTC, wxsms commented on src/style-guide/README.md
> +- 因为这些组件会被频繁使用，所以你可能想要把它们注册到全局，而不是在各处分别导入它们。结合一个前缀即可使用 Webpack 达到目的：
刚刚在 wiki 中发现了，抱歉。

2021-08-16 14:06 UTC, wxsms commented
@Justineo 感谢细致的 review，提出了很多非常好的建议，学习了。另外，某些建议我作出了一些微调，并标注为了 unresolved，如果你没有意见的话可以把它们 resolve 掉哈。

2021-08-16 15:46 UTC, veaba commented
@wxsms 可以点 Tab `Files changed` 来批量应用 Suggestion，避免一个 commit  一个 apply suggestion。

参考：
![image](https://user-images.githubusercontent.com/8652596/129591411-2d4044bb-6cf7-4f44-8406-b275eae7d8e2.png)

2021-08-17 01:19 UTC, wxsms commented
@veaba 啊，刚知道有这个功能。谢谢。以后知道该怎么做了。

2021-08-17 04:30 UTC, Justineo commented on src/style-guide/README.md
> +这样做可以跟现有的，以及未来的 HTML 元素[避免冲突](https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name)，因为所有的 HTML 元素名称都是单个单词的。
应该是的，我写漏了

2021-08-17 04:30 UTC, Justineo commented on src/style-guide/README.md
> +  小的，且更专注的计算属性减少了对信息将如何被使用的猜测，因此当需求变更时，重构的工作量也将更小。
ok

2021-08-21 02:12 UTC, merged