Translated "migration build" page
vuejs/docs-next-zh-cn pull request #624
Opened 2021-08-08 12:02 UTC by Jinjiang

## Description of Problem

- `src/guide/migration/global-api.md`
- `src/guide/migration/migration-build.md`

## Proposed Solution

## Additional Information

2021-08-09 02:12 UTC, wxsms requested changes
一些小建议

2021-08-09 02:12 UTC, wxsms commented on src/guide/migration/migration-build.md
> +| COMPILER_V_FOR_TEMPLATE_KEY_PLACEMENT | ⨂    | `<template v-for>` key 现在应该放在 `<template>` 上 | [链接](/guide/migration/key-attribute.html#with-template-v-for)                                |
应该放在 -> 应该被放在

2021-08-09 02:12 UTC, wxsms commented on src/guide/migration/migration-build.md
> +| CONFIG_IGNORED_ELEMENTS  | ◐    | `config.ignoredElements` 现在成为了 `config.compilerOptions.isCustomElement` (只在浏览器编译器构建中)。如果使用构建设置，`isCustomElement` 必须通过构建配置传入。 | [链接](/guide/migration/global-api.htm
`config.ignoredElements` 现在成为了 -> `config.ignoredElements` 现在改为了

2021-08-09 02:12 UTC, wxsms commented on src/guide/migration/migration-build.md
> +| CONFIG_IGNORED_ELEMENTS  | ◐    | `config.ignoredElements` 现在成为了 `config.compilerOptions.isCustomElement` (只在浏览器编译器构建中)。如果使用构建设置，`isCustomElement` 必须通过构建配置传入。 | [链接](/guide/migration/global-api.htm
如果使用构建设置 -> 如果使用了构建设置

2021-08-09 02:12 UTC, wxsms commented on src/guide/migration/migration-build.md
> +| CONFIG_PRODUCTION_TIP    | ◐    | `config.productionTip` 不再需要 | [链接](/guide/migration/global-api.html#config-productiontip-移除) |
`config.productionTip` 不再需要 -> 不再需要 `config.productionTip`

2021-08-09 02:12 UTC, wxsms commented on src/guide/migration/migration-build.md
> +| TRANSITION_CLASSES | ⭘    | 过渡动画的进入/离开类发生了变化 | [链接](/guide/migration/transition.html) |
进入/离开类 -> 进入/离开的 class

我发现目前文档中挺多 css class 是没有翻译为“类”的，仅供参考。

2021-08-09 02:12 UTC, wxsms commented on src/guide/migration/migration-build.md
> +| WATCH_ARRAY                  | ✔    | watching an array no longer triggers on mutation unless deep | [链接](/guide/migration/watch.html) |
对于一个数组的操作，监听无法被触发了，除非使用了深度监听

2021-08-09 02:12 UTC, wxsms commented on src/guide/migration/migration-build.md
> +| COMPONENT_FUNCTIONAL         | ✔    | 函数式组件 API 改变 (目前必须是单纯的函数) | [链接](/guide/migration/functional-components.html) |
单纯的函数 -> 纯函数

2021-08-09 03:59 UTC, Justineo requested changes

2021-08-09 03:59 UTC, Justineo commented on src/guide/migration/migration-build.md
> +当我们全力尝试让该迁移构建模拟尽可能多的 Vue 2 行为的时候，有些限制可能会阻止应用的顺利升级：
```suggestion
虽然我们已经努力使迁移构建尽可能地模拟 Vue 2 的行为，但仍有一些限制可能会阻止应用的顺利升级：
```

2021-08-09 03:59 UTC, Justineo commented on src/guide/migration/migration-build.md
> +- 基于 Vue 2 内部 API 或未成文的行为的依赖。最常见的情况就是使用 `VNodes` 上的私有 property。如果你的项目依赖诸如 [Vuetify](https://vuetifyjs.com/zh-Hans/)、[Quasar](https://quasar.dev/) 或 [ElementUI](https://element.eleme.io/#/zh-CN) 的组件库，
```suggestion
- 基于 Vue 2 内部 API 或文档中未记载行为的依赖。最常见的情况就是使用 `VNodes` 上的私有 property。如果你的项目依赖诸如 [Vuetify](https://vuetifyjs.com/zh-Hans/)、[Quasar](https://quasar.dev/) 或 [Element UI](https://element.eleme.io/#/zh-CN) 等组件库，那么最好等待一下它们的 Vue 3 兼容版本。
```

2021-08-09 03:59 UTC, Justineo commented on src/guide/migration/migration-build.md
> +请注意迁移构建旨在覆盖公开成文的 Vue 2 API 和行为。如果应用依赖了未成文的行为导致在迁移构建下运行失败，我们可能不太会调整迁移构建以迎合这种特殊情况。取而代之的是，请考虑重构或移除导致这些问题行为的依赖。
```suggestion
请注意迁移构建旨在覆盖在文档中公开记载的 Vue 2 API 和行为。如果应用依赖了未记载的行为导致在迁移构建下运行失败，我们可能不太会调整迁移构建以迎合这种特殊情况。请考虑重构或移除导致这些问题行为的依赖。
```

“instead” 感觉在这里不用翻译。

2021-08-09 03:59 UTC, Justineo commented on src/guide/migration/migration-build.md
> +多留意一下：如果你的应用较大且复杂，即便有了构建迁移，整个迁移过程也会是一个挑战。如果你的应用不幸无法顺利升级，请留意我们正在计划将组合式 API 等其它 Vue 3 特性向后迁移至 Vue 2.7 (预计在 2021 年第三季度末)。
```suggestion
多留意一下：如果你的应用较大且复杂，即便有了构建迁移，整个迁移过程也会是一个挑战。如果你的应用不幸无法顺利升级，请留意我们正在计划将组合式 API 等其它 Vue 3 特性迁移回 Vue 2.7 (预计在 2021 年第三季度末)。
```

2021-08-09 03:59 UTC, Justineo commented on src/guide/migration/migration-build.md
> +如果应用在迁移构建中顺利运行，你**可以**在迁移完成之前将其发布到生产环境。尽管存在一些小的性能或包大小的问题，但应该不会可观地影响到生产环境的用户体验。你可能需要为基于 Vue 2 行为且无法升级/替换的依赖这样做。
```suggestion
如果应用在迁移构建中顺利运行，你**可以**在迁移完成之前将其发布到生产环境。尽管存在一些小的性能或包大小的问题，但应该不会可观地影响到生产环境的用户体验。当你有基于 Vue 2 行为的依赖且无法升级/替换时，可能不得不这样做。
```

2021-08-09 03:59 UTC, Justineo commented on src/guide/migration/migration-build.md
>  The following workflow walks through the steps of migrating an actual Vue 2 app (Vue HackerNews 2.0) to Vue 3. The full commits can be found [here](https://github.com/vuejs/vue-hackernews-2.0/compare
```suggestion
下面的工作流程讲述了将一个实际的 Vue 2 应用（Vue HackerNews 2.0）迁移到 Vue 3 的过程。完整的提交记录在[这里](https://github.com/vuejs/vue-hackernews-2.0/compare/migration)。请注意，你的项目所需要的实际步骤可能有所不同。下面的步骤仅应被视为一般性的指南，而非严格的教程。
```

guidance 和 instruction 这两个词我这里没有严格翻译，可以讨论下有没有更好的译法。通常中文里的“教程”在 web 开发/设计领域都会是指那种一步步照做就可以完成的，类似 tutorial。

2021-08-09 03:59 UTC, Justineo commented on src/guide/migration/migration-build.md
>  - If you are still using the [deprecated named / scoped slot syntax](https://vuejs.org/v2/guide/components-slots.html#Deprecated-Syntax), update it to the latest syntax first (which is already suppor
```suggestion
```

2021-08-09 03:59 UTC, Justineo commented on src/guide/migration/migration-build.md
> +2. 在 `package.json` 里，更新 `vue` 到 3.1，安装 `@vue/compat` 相同的版本，且如果存在 `vue-template-compiler` 的话，将其替换为 `@vue/compiler-sfc`。
```suggestion
2. 在 `package.json` 里，将 `vue` 更新到 3.1，安装相同版本的 `@vue/compat`。且如果存在 `vue-template-compiler` 的话，将其替换为 `@vue/compiler-sfc`。
```

2021-08-09 03:59 UTC, Justineo commented on src/guide/migration/migration-build.md
> +   - 你可以在浏览器控制台里过滤特定的警告。通过过滤器使自己每次专注在某一种问题的修复上是个不错的主意。你也可以使用类似 `-GLOBAL_MOUNT` 的否定式过滤器。
```suggestion
   - 你可以在浏览器控制台里过滤特定的警告。建议通过使用过滤器，使自己每次专注修复同一种问题。你也可以使用类似 `-GLOBAL_MOUNT` 的否定式过滤器。
```

“It's a good idea to” 直译的话感觉会是太明显的翻译腔，用“建议……”会不会好一点？

2021-08-09 03:59 UTC, Justineo commented on src/guide/migration/migration-build.md
> +   - 你可以通过[兼容性配置](#兼容性配置)抑制特定的废弃内容。
```suggestion
   - 你可以通过[兼容性配置](#兼容性配置)关闭对特定的废弃内容的处理。
```

补充意译了一下

2021-08-09 03:59 UTC, Justineo commented on src/guide/migration/migration-build.md
> +   - 有些警告可能来自你使用的依赖 (如 `vue-router`)。你可以通过警告的组件轨迹或调用栈轨迹 (可以点击展开) 来进行检查。可以优先专注于修复源自你自己代码的警告。
```suggestion
   - 有些警告可能来自你使用的依赖 (如 `vue-router`)。你可以通过警告的组件嵌套或调用栈的追踪信息 (可以点击展开) 来进行检查。可以优先专注于修复源自你自己代码的警告。
```

2021-08-09 03:59 UTC, Justineo commented on src/guide/migration/migration-build.md
> +8. [升级 `vuex` 至 v4](https://next.vuex.vuejs.org/guide/migrating-to-4-0-from-3-x.html)。
```suggestion
8. [将 `vuex` 升级至 v4](https://next.vuex.vuejs.org/zh/guide/migrating-to-4-0-from-3-x.html)。
```

2021-08-09 03:59 UTC, Justineo commented on src/guide/migration/migration-build.md
> +9. [升级 `vue-router` 至 v4](https://next.router.vuejs.org/guide/migration/index.html)。如果你还适用了 `vuex-router-sync`，可以同时将其替换为一个 store getter。
```suggestion
9. [将 `vue-router` 升级至 v4](https://next.router.vuejs.org/zh/guide/migration/index.html)。如果你还使用了 `vuex-router-sync`，可以同时将其替换为一个 store getter。
```

2021-08-09 03:59 UTC, Justineo commented on src/guide/migration/migration-build.md
> +7. 更新应用的入口以使用[新的全局挂载 API](/guide/migration/global-api.html#a-new-global-api-createapp)。
```suggestion
7. 更新应用的入口以使用[新的全局挂载 API](https://v3.cn.vuejs.org/guide/migration/global-api.html#%E4%B8%80%E4%B8%AA%E6%96%B0%E7%9A%84%E5%85%A8%E5%B1%80-api-createapp)。
```

2021-08-09 03:59 UTC, Justineo commented on src/guide/migration/migration-build.md
> +   升级过后，同 `<router-view>` 一起使用 `<transition>` 和 `<keep-alive>` 就要求使用新的[基于作用域插槽的语法](https://next.router.vuejs.org/guide/migration/index.html#router-view-keep-alive-and-transition)。
```suggestion
   升级过后，同 `<router-view>` 一起使用 `<transition>` 和 `<keep-alive>` 就要求使用新的[基于作用域插槽的语法](https://next.router.vuejs.org/zh/guide/migration/index.html#router-view-%E3%80%81-keep-alive-%E5%92%8C-transition)。
```

2021-08-09 03:59 UTC, Justineo commented on src/guide/migration/migration-build.md
> +10. 单独警告单独处理。注意有些特性在 Vue 2 和 Vue 3 之间存在行为冲突——例如渲染函数 API，或函数式组件 vs. 异步组件的改变。为了迁移到 Vue 3 API 而不影响到应用的其它部分，你可以通过 [`compatConfig` 选项](#基于单个组件的配置)对单个组件选入 Vue 3 的行为。
```suggestion
10. 逐个修复警告。注意有些特性在 Vue 2 和 Vue 3 之间存在行为冲突——例如渲染函数 API，或函数式组件 vs. 异步组件的改变。为了迁移到 Vue 3 API 而不影响到应用的其它部分，你可以通过 [`compatConfig` 选项](#基于单个组件的配置)对单个组件选择性启用 Vue 3 的行为。
```

做了一些意译，和下文的“所有警告都被修复”对应。

2021-08-09 03:59 UTC, Justineo commented on src/guide/migration/migration-build.md
> +11. 当所有的警告都被修复时，你可以正确地移除迁移构建而切换为 Vue 3。注意如果存在基于 Vue 2 行为的依赖，你可能无法做到这一点。
```suggestion
11. 当修复了所有警告以后，你就可以移除迁移构建并切换为 Vue 3。注意如果存在基于 Vue 2 行为的依赖，你可能无法做到这一点。
```

(原文是不是错了，感觉应该是 properly)

2021-08-09 03:59 UTC, Justineo commented on src/guide/migration/migration-build.md
> +    MODE: 3, // 只为这个组件选入 Vue 3 行为
```suggestion
    MODE: 3, // 只为这个组件选择性启用 Vue 3 行为
```

2021-08-09 03:59 UTC, Justineo commented on src/guide/migration/migration-build.md
> +| CONFIG_DEVTOOLS                       | ⨂    | 生产环境开发者工具现在是一个构建时的标记 | [链接](https://github.com/vuejs/vue-next/tree/master/packages/vue#bundler-build-feature-flags) |
```suggestion
| CONFIG_DEVTOOLS                       | ⨂    | 生产环境开发者工具现在是一个构建时的开关 | [链接](https://github.com/vuejs/vue-next/tree/master/packages/vue#bundler-build-feature-flags) |
```

2021-08-09 03:59 UTC, Justineo commented on src/guide/migration/global-api.md
> +[迁移构建标记：`GLOBAL_PROTOTYPE`](migration-build.html#兼容性配置)
```suggestion
[迁移构建开关：`GLOBAL_PROTOTYPE`](migration-build.html#兼容性配置)
```

只看中文，“标记”应该很难理解

2021-08-09 03:59 UTC, Justineo commented on src/guide/migration/migration-build.md
> +| COMPILER_SFC_FUNCTIONAL               | ⨂    | `<template functional>` 在单文件组件中不再被支持 | [链接](/guide/migration/functional-components.html#single-file-components-sfcs)                |
```suggestion
| COMPILER_SFC_FUNCTIONAL               | ⨂    | 单文件组件中不再支持 `<template functional>` | [链接](/guide/migration/functional-components.html#single-file-components-sfcs)                |
```

2021-08-09 03:59 UTC, Justineo commented on src/guide/migration/migration-build.md
> +| ATTR_ENUMERATED_COERCION     | ✔    | No longer special case enumerated attributes | [链接](/guide/migration/attribute-coercion.html) |
```suggestion
| ATTR_ENUMERATED_COERCION     | ✔    | 不再特殊处理枚举类型 attribute | [链接](/guide/migration/attribute-coercion.html) |
```

2021-08-09 04:06 UTC, Jinjiang commented on src/guide/migration/migration-build.md
> +# 迁移构建
恩，支持讨论一下。印象中 installation 页面里应该大部分名词也都翻译成了构建，一直有点纠结。

2021-08-09 04:24 UTC, Jinjiang commented on src/guide/migration/global-api.md
> +[迁移构建标记：`GLOBAL_PROTOTYPE`](migration-build.html#兼容性配置)
恩，认同。目前所有的 flag 应该都翻译成标记了，可能需要统一处理一下

2021-08-09 04:29 UTC, Jinjiang commented on src/guide/migration/migration-build.md
> +如果应用在迁移构建中顺利运行，你**可以**在迁移完成之前将其发布到生产环境。尽管存在一些小的性能或包大小的问题，但应该不会可观地影响到生产环境的用户体验。你可能需要为基于 Vue 2 行为且无法升级/替换的依赖这样做。
```suggestion
如果应用在迁移构建中顺利运行，你**可以**在迁移完成之前将其发布到生产环境。尽管存在一些小的性能或包大小的问题，但应该不会显著地影响到生产环境的用户体验。当你有基于 Vue 2 行为的依赖且无法升级/替换时，可能不得不这样做。
```

中和了一下二位的意见

2021-08-09 04:31 UTC, Jinjiang commented on src/guide/migration/migration-build.md
>  The following workflow walks through the steps of migrating an actual Vue 2 app (Vue HackerNews 2.0) to Vue 3. The full commits can be found [here](https://github.com/vuejs/vue-hackernews-2.0/compare
我觉得这里没什么问题，这几个词不是专有名词，即便混用也不影响理解

2021-08-09 04:39 UTC, Jinjiang commented on src/guide/migration/migration-build.md
> +| COMPONENT_FUNCTIONAL         | ✔    | 函数式组件 API 改变 (目前必须是单纯的函数) | [链接](/guide/migration/functional-components.html) |
纯函数应该指的是 pure function，我理解这里的 plain 应该不是那个意思，它指的是：`{ functional: true, render() {...} }` 这种写法不再被支持了

2021-08-09 04:42 UTC, Justineo commented on src/guide/migration/migration-build.md
> +| COMPONENT_FUNCTIONAL         | ✔    | 函数式组件 API 改变 (目前必须是单纯的函数) | [链接](/guide/migration/functional-components.html) |
我觉得“现在必须是函数”就好。另外这里的几个“目前”应该都改成“现在”比较好，“目前”听上去未来会变化。

2021-08-09 04:42 UTC, wxsms commented on src/guide/migration/migration-build.md
> +| COMPONENT_FUNCTIONAL         | ✔    | 函数式组件 API 改变 (目前必须是单纯的函数) | [链接](/guide/migration/functional-components.html) |
有道理。

2021-08-09 04:47 UTC, Jinjiang commented on src/guide/migration/migration-build.md
> +# 迁移构建
不介意的话我把这个话题从这个 PR 单独拿出去讨论了 #628

2021-08-09 04:50 UTC, wxsms commented on src/guide/migration/migration-build.md
> +# 迁移构建
可以参考v2文档：https://cn.vuejs.org/v2/guide/installation.html#%E5%AF%B9%E4%B8%8D%E5%90%8C%E6%9E%84%E5%BB%BA%E7%89%88%E6%9C%AC%E7%9A%84%E8%A7%A3%E9%87%8A

此处，builds 被翻译为了“构建版本”。如果按照这个规则来说，这里应该叫“迁移构建版本”。

不过我个人认为依然是有些难以理解。“用于迁移的构建版本”是否更好呢？

2021-08-09 04:52 UTC, Jinjiang commented on src/guide/migration/migration-build.md
> +# 迁移构建
构建版本我觉得可以接受

2021-08-09 04:53 UTC, Jinjiang commented on src/guide/migration/migration-build.md
> +| COMPONENT_FUNCTIONAL         | ✔    | 函数式组件 API 改变 (目前必须是单纯的函数) | [链接](/guide/migration/functional-components.html) |
那多展开一下吧，其实是个老问题了：plain object 大家觉得怎么翻译

2021-08-09 04:54 UTC, Jinjiang commented on src/guide/migration/migration-build.md
> +# 迁移构建
Anyway，不介意的话我们先在 #628 讨论？我希望这次讨论得充分一些，可以有更多人参与一下。

2021-08-09 04:56 UTC, wxsms commented on src/guide/migration/migration-build.md
> +# 迁移构建
> Anyway，不介意的话我们先在 #628 讨论？我希望这次讨论得充分一些，可以有更多人参与一下。

好的，我把我的评论copy过去。

2021-08-09 06:11 UTC, Jinjiang commented on src/guide/migration/migration-build.md
> +| COMPONENT_FUNCTIONAL         | ✔    | 函数式组件 API 改变 (目前必须是单纯的函数) | [链接](/guide/migration/functional-components.html) |
```suggestion
| COMPONENT_FUNCTIONAL         | ✔    | 函数式组件 API 改变 (现在必须只是一个单纯的函数) | [链接](/guide/migration/functional-components.html) |
```

@Justineo 我可能还是倾向于强调一下是“单纯的函数”，因为感觉“函数”这个词本身表达不出原文想强调的意思。我又提供了一版译法，你看如何。

2021-08-09 06:35 UTC, Justineo commented on src/guide/migration/migration-build.md
> +| COMPONENT_FUNCTIONAL         | ✔    | 函数式组件 API 改变 (目前必须是单纯的函数) | [链接](/guide/migration/functional-components.html) |
普通函数？plain object 可以翻译成普通对象。

2021-08-09 07:50 UTC, Jinjiang commented on src/guide/migration/migration-build.md
> +| COMPONENT_FUNCTIONAL         | ✔    | 函数式组件 API 改变 (目前必须是单纯的函数) | [链接](/guide/migration/functional-components.html) |
deal

2021-08-11 09:18 UTC, merged

2021-08-11 09:19 UTC, Justineo commented
没有了，已合