docs: update
vuejs/docs-next-zh-cn pull request #630
Opened 2021-08-09 09:54 UTC by yugasun

## Description of Problem

## Proposed Solution

## Additional Information

2021-08-10 03:15 UTC, veaba commented on src/guide/migration/inline-template-attribute.md
> +> - 提示：在 3.x，插槽可以渲染为具有原生 [fragments](/guide/migration/fragments.html) 支持的根目录！
这里其实可以不用补齐。

2021-08-10 03:45 UTC, wxsms requested changes

2021-08-10 03:45 UTC, wxsms commented on src/guide/migration/inline-template-attribute.md
> +> - 提示：在 3.x，插槽可以渲染为具有原生 [fragments](/guide/migration/fragments.html) 支持的根目录！
```suggestion
> - 提示：在 3.x，插槽可以渲染为具有原生[片段](/guide/migration/fragments)支持的根目录！
```

/guide/migration/fragments 的标题为”片段“，因此这里是否也可以翻译为”片段“？避免跳转前看到的是 fragments，跳转后看到的标题是”片段“。

2021-08-11 09:07 UTC, Jinjiang commented on src/guide/migration/inline-template-attribute.md
> +> - 提示：在 3.x，插槽可以渲染为具有原生 [片段](/guide/migration/fragments) 支持的根目录！
```suggestion
> - 提示：在 3.x，插槽可以渲染为具有原生[片段](/guide/migration/fragments)支持的根目录！
```

2021-08-11 09:08 UTC, Jinjiang approved these changes

2021-08-11 09:08 UTC, merged