Translated new parts of computed-watch-api and directives api
vuejs/docs-next-zh-cn pull request #647
Opened 2021-08-15 03:33 UTC by Jinjiang

## Description of Problem

- `src/api/computed-watch-api`
- `src/api/directives`

## Proposed Solution

## Additional Information

2021-08-16 01:31 UTC, wxsms commented
`v-memo` 这部分我也翻译了，早前提交了 PR，可以看看是否可以互补？

2021-08-18 02:42 UTC, wxsms requested changes

2021-08-18 02:42 UTC, wxsms commented on src/api/computed-watch-api.md
> +`watchEffect` 带有 `flush: 'post'` 选项的别名。
```suggestion
`watchEffect` 的别名，带有 `flush: 'post'` 选项。
```

语序调换一下好像好一些？下同

2021-08-18 02:42 UTC, wxsms commented on src/api/computed-watch-api.md
> +`watchEffect` 带有 `flush: 'sync'` 选项的别名。
```suggestion
`watchEffect` 的别名，带有 `flush: 'sync'` 选项。
```

2021-08-21 01:12 UTC, Jinjiang commented
> `v-memo` 这部分我也翻译了，早前提交了 PR #640 ，也许可以看看是否可以互补？

👌没问题，以你的为准吧，辛苦了

2021-08-21 02:25 UTC, Justineo requested changes

2021-08-21 02:25 UTC, Justineo commented on src/api/directives.md
> +  从 3.2 开始，你也可以使用 [`v-memo`](#v-memo) 记住模板的无效条件的那部分。
```suggestion
  从 3.2 开始，你也可以使用 [`v-memo`](#v-memo) 定义失效条件，来对模板的一部分进行 memoize。
```

memoize 翻译了我感觉绝大多数人是看不懂的了……要不这个也作为保留不翻译的一部分？

2021-08-21 02:25 UTC, Justineo commented on src/api/directives.md
> +  从 3.2 开始，你也可以使用 [`v-memo`](#v-memo) 记住模板的无效条件的那部分。
或者翻译成“缓存”？这又会和 cache 产生一些歧义。

2021-08-21 02:25 UTC, Justineo commented on src/api/directives.md
> +  记住一个模板的子树。元素和组件上都可以使用。该指令接收一个固定长度的数组作为依赖值进行记忆比对。如果数组中的每个值都和上次渲染的时候相同，则整个该子树的更新会被跳过。例如：
依赖 memoize 怎么处理还需要做些调整。

2021-08-21 02:25 UTC, Justineo commented on src/api/directives.md
> +  当组件被重新渲染时，如果 `valueA` 和 `valueB` 都还是原来的值，则这个 `<div>` 及其子元素的所有更新将会被跳过。实际上，甚至连 Virtual DOM 的 VNode 创建也会被跳过，因为被记住的子树的拷贝是可复用的。
其他地方 virtual 翻译了么？

2021-08-21 02:25 UTC, Justineo commented on src/api/directives.md
> +  `v-memo` 仅供性能优先场景的微观优化，这种需求应该是罕见的。最常见的有帮助的情况是渲染 `v-for` 长列表 (长度大于 1000)：
```suggestion
  `v-memo` 仅供性能敏感场景的针对性优化，会用到场景很少。渲染 `v-for` 长列表 (长度大于 1000) 可能是它最有用的场景：
```

2021-08-21 06:54 UTC, veaba commented on src/api/directives.md
> +  从 3.2 开始，你也可以使用 [`v-memo`](#v-memo) 记住模板的无效条件的那部分。
遇事不决，可来个“化”：记忆化。:joy:

2021-08-21 15:58 UTC, Jinjiang commented on src/api/directives.md
> +  从 3.2 开始，你也可以使用 [`v-memo`](#v-memo) 记住模板的无效条件的那部分。
首先我觉得保留 memorize 似乎行不通，第一它不是专有名词，第二它也很难说是被中文读者广泛认知的常用词汇。
其次译为“记住”我个人还觉得蛮贴切的，而且这是我能查到的 (牛津英汉词典) 唯一中文译法。

2021-08-21 15:58 UTC, Jinjiang commented on src/api/directives.md
> +  当组件被重新渲染时，如果 `valueA` 和 `valueB` 都还是原来的值，则这个 `<div>` 及其子元素的所有更新将会被跳过。实际上，甚至连 Virtual DOM 的 VNode 创建也会被跳过，因为被记住的子树的拷贝是可复用的。
```suggestion
  当组件被重新渲染时，如果 `valueA` 和 `valueB` 都还是原来的值，则这个 `<div>` 及其子元素的所有更新将会被跳过。实际上，甚至连虚拟 DOM 的 VNode 创建也会被跳过，因为被记住的子树的拷贝是可复用的。
```
查了一下，翻译了。我改一下

Ref：https://v3.cn.vuejs.org/guide/optimizations.html#虚拟-dom

2021-08-21 16:03 UTC, Jinjiang commented on src/api/directives.md
> +  从 3.2 开始，你也可以使用 [`v-memo`](#v-memo) 记住模板的无效条件的那部分。
补充一些，发现 #640 翻译的也是“记住”

2021-08-21 16:04 UTC, Jinjiang commented on src/api/directives.md
> +  记住一个模板的子树。元素和组件上都可以使用。该指令接收一个固定长度的数组作为依赖值进行记忆比对。如果数组中的每个值都和上次渲染的时候相同，则整个该子树的更新会被跳过。例如：
@wxsms  不介意的话也参与一下这里的讨论吧，虽然已经 merge 过了

2021-08-21 16:10 UTC, Jinjiang commented
@Justineo @wxsms 我把 master 分支的改动同步过来了，这次合并我以 master 的翻译为主，在此基础上针对这里产生讨论的几个点上做了更新。有劳 double check 一下，谢谢。

2021-08-21 17:11 UTC, Justineo commented on src/api/directives.md
> +  从 3.2 开始，你也可以使用 [`v-memo`](#v-memo) 记住模板的无效条件的那部分。
我是这样想的，用“memoize”一是可以解释为什么叫 `v-memo`，二是至少用 memoize 去搜索引擎还能搜到意思，用“记住”就完全不知道到底是怎么回事了……

2021-08-21 20:05 UTC, Jinjiang commented on src/api/directives.md
> +  从 3.2 开始，你也可以使用 [`v-memo`](#v-memo) 记住模板的无效条件的那部分。
感觉你的想法背后是希望 memorize 这个词能够和 v-memo 产生某种直接的关联，不只是自然语言描述，我个人觉得不是特别有必要啦。不知道大家怎么看：）

2021-08-22 04:15 UTC, wxsms commented on src/api/directives.md
> +  记住一个模板的子树。元素和组件上都可以使用。该指令接收一个固定长度的数组作为依赖值进行记忆比对。如果数组中的每个值都和上次渲染的时候相同，则整个该子树的更新会被跳过。例如：
https://zh-hans.reactjs.org/docs/hooks-reference.html#usememo

提供一个参考，react 文档没有翻译 memoize 这个词。

不过，我个人认为翻译成“记住”也并无不妥。概念应该是吻合的。

提一个折中的建议，翻译为记住，但也在后面跟括号，括号内保留原文。不知道是否可行？

2021-08-22 04:31 UTC, Justineo commented on src/api/directives.md
> +  从 3.2 开始，你也可以使用 [`v-memo`](#v-memo) 记住模板的无效条件的那部分。
我又想了一下，其实 memoize 是一种特殊的 cache 逻辑，这个地方如果翻译成“缓存”，从中文来看是不是也更容易理解？而且缓存一般都是有失效逻辑的，和 invalidation condition 也算对应。

2021-08-22 04:38 UTC, wxsms requested changes

2021-08-22 04:38 UTC, wxsms commented on src/api/directives.md
> +  正确地声明记忆数组是很重要的，否则应有更新也可能会被错过。带有空依赖数组的 `v-memo` (`v-memo="[]"`) 在功能上等效于 `v-once`。
此处我更倾向于原本的翻译，也许更加契合原文的意思。

2021-08-22 04:38 UTC, wxsms commented on src/api/directives.md
> +  `v-memo` 仅供性能敏感场景的针对性优化，会用到场景很少。渲染 `v-for` 长列表 (长度大于 1000) 可能是它最有用的场景：
```suggestion
  `v-memo` 仅供性能敏感场景的针对性优化，会用到的场景应该很少。渲染 `v-for` 长列表 (长度大于 1000) 可能是它最有用的场景：
```

2021-08-22 04:48 UTC, wxsms commented on src/api/directives.md
> +  从 3.2 开始，你也可以使用 [`v-memo`](#v-memo) 记住模板的无效条件的那部分。
> 我又想了一下，其实 memoize 是一种特殊的 cache 逻辑，这个地方如果翻译成“缓存”，从中文来看是不是也更容易理解？而且缓存一般都是有失效逻辑的，和 invalidation condition 也算对应。

我觉得不妥。缓存这个词第一反应就是 cache，虽然意义接近，但总归来说有些偏差。并且指令名是memo，不是cache。如果要翻译的话，突出记住、记忆我觉得才是“可信”的。

2021-08-22 04:51 UTC, Justineo commented on src/api/directives.md
> +  从 3.2 开始，你也可以使用 [`v-memo`](#v-memo) 记住模板的无效条件的那部分。
因为这里的逻辑其实就是cache。

2021-08-29 05:37 UTC, Jinjiang commented on src/api/directives.md
> +  正确地声明记忆数组是很重要的，否则应有更新也可能会被错过。带有空依赖数组的 `v-memo` (`v-memo="[]"`) 在功能上等效于 `v-once`。
```suggestion
  正确地声明记忆数组是很重要的，否则某些事实上需要被应用的更新也可能会被跳。带有空依赖数组的 `v-memo` (`v-memo="[]"`) 在功能上等效于 `v-once`。
```

2021-08-29 05:40 UTC, Jinjiang commented on src/api/directives.md
> +  从 3.2 开始，你也可以使用 [`v-memo`](#v-memo) 记住模板的无效条件的那部分。
个人感觉整体看下来还是“记住”比较好。我们不然再针对这个译法单独开个讨论好了，其它的部分我先 merge 了

2021-08-29 05:41 UTC, Jinjiang commented on src/api/directives.md
> +  记住一个模板的子树。元素和组件上都可以使用。该指令接收一个固定长度的数组作为依赖值进行记忆比对。如果数组中的每个值都和上次渲染的时候相同，则整个该子树的更新会被跳过。例如：
感觉保留 memorize 或追加括号也有点奇怪，建议先保留目前的译法“记住”，后续讨论可以单独看 issue，参考 L467 的讨论。

2021-08-29 05:43 UTC, merged