docs: translate sfc-script-setup.md
vuejs/docs-next-zh-cn pull request #652
Opened 2021-08-16 09:20 UTC by arronKler

translated sfc-script-setup.md file

2021-08-17 06:42 UTC, renmu123 commented on src/api/sfc-script-setup.md
> +响应式状态需要明确使用[响应式 APIs](/api/basic-reactivity.html) 来创建。和从 `setup()` 函数中返回值一样，ref 值在模板中使用的时候会自动拆箱：
和从 `setup()` 函数中返回值一样，ref 值在模板中使用时会被自动展开：

2021-08-17 06:42 UTC, renmu123 commented on src/api/sfc-script-setup.md
> +将 `MyComponent` 看做被一个变量所引用。如果使用了 JSX，在这里的使用它的心智模型是一样的。其 kebab-case 格式的 `<my-component>` 同样能在模板中使用。不过，我们强烈建议使用 PascalCase 格式作为组件的标签名称，以便于更好的一致性，同时也有助于区分原生的自定义元素。
这个“心智模型”的翻译很奇怪。

不过，我们强烈推荐使用 PascalCase 格式作为组件的标签名称，由于其更好的一致性以及能与原生的自定义元素区分开。

2021-08-17 07:13 UTC, Justineo commented on src/api/sfc-script-setup.md
> +将 `MyComponent` 看做被一个变量所引用。如果使用了 JSX，在这里的使用它的心智模型是一样的。其 kebab-case 格式的 `<my-component>` 同样能在模板中使用。不过，我们强烈建议使用 PascalCase 格式作为组件的标签名称，以便于更好的一致性，同时也有助于区分原生的自定义元素。
mental model 翻译成“心智模型”应该是个固定搭配了：https://zh.wikipedia.org/wiki/%E5%BF%83%E6%99%BA%E6%A8%A1%E5%9E%8B

2021-08-17 07:24 UTC, renmu123 commented on src/api/sfc-script-setup.md
> +将 `MyComponent` 看做被一个变量所引用。如果使用了 JSX，在这里的使用它的心智模型是一样的。其 kebab-case 格式的 `<my-component>` 同样能在模板中使用。不过，我们强烈建议使用 PascalCase 格式作为组件的标签名称，以便于更好的一致性，同时也有助于区分原生的自定义元素。
ok

2021-08-19 07:32 UTC, veaba requested changes

2021-08-19 07:32 UTC, veaba commented on src/api/sfc-script-setup.md
> +响应式状态需要明确使用[响应式 APIs](/api/basic-reactivity.html) 来创建。和从 `setup()` 函数中返回值一样，ref 值在模板中使用的时候会自动展开：
```suggestion
响应式状态需要明确使用[响应式 APIs](/api/basic-reactivity.html) 来创建。和从 `setup()` 函数中返回值一样，ref 值在模板中使用的时候会自动解包：
```
unwrap 有固定的约定，see wiki

2021-08-19 07:32 UTC, veaba commented on src/api/sfc-script-setup.md
> +当父组件通过模板 ref 的方式获取到当前组件的实例，获取到的实例会像这样 `{ a: number, b: number }` (ref 会和在普通实例中一样被自动展开)
```suggestion
当父组件通过模板 ref 的方式获取到当前组件的实例，获取到的实例会像这样 `{ a: number, b: number }` (ref 会和在普通实例中一样被自动解包)
```
同上

2021-08-19 09:47 UTC, veaba approved these changes

2021-08-19 09:48 UTC, merged