docs: translate sfc-style.md
vuejs/docs-next-zh-cn pull request #653
Opened 2021-08-16 10:30 UTC by arronKler

translated sfc-style.md file

2021-08-17 02:48 UTC, wxsms requested changes

2021-08-17 02:48 UTC, wxsms commented on src/api/sfc-style.md
> +当 `<style>` 标签有 `scoped` 特性的时候，它的 CSS 只会应用到当前组件的元素上。这类似于 Shadow DOM 中的样式封装。它带有一些警告，但是并不需要任何的 polyfill。它是通过 PostCSS 转换以下内容来实现的：
```suggestion
当 `<style>` 标签带有 `scoped` attribute 的时候，它的 CSS 只会应用到当前组件的元素上。这类似于 Shadow DOM 中的样式封装。它带有一些注意事项，不过好处是不需要任何的 polyfill。它是通过 PostCSS 转换以下内容来实现的：
```

根据 wiki，attribute 是不翻译的

2021-08-17 02:48 UTC, wxsms commented on src/api/sfc-style.md
> +在有 `scoped` 的时候，父组件的样式将不会泄露到子组件当中。不过，子组件的根节点会同时被父组件的作用域样式和子组件的作用域样式影响。这是特意设计的，这样父组件就可以设置子组件根节点的样式来达到调整布局的目的。
```suggestion
在带有 `scoped` 的时候，父组件的样式将不会泄露到子组件当中。不过，子组件的根节点会同时被父组件的作用域样式和子组件的作用域样式影响。这是有意为之的，这样父组件就可以设置子组件根节点的样式，以达到调整布局的目的。
```

2021-08-17 02:48 UTC, wxsms commented on src/api/sfc-style.md
> +如果你想要在 `scoped` 的样式里的选择器能做更“深度”的选择，也即：影响到子组件，你可以使用 `:deep()` 这个伪类：
```suggestion
处于 `scoped` 样式中的选择器如果想要做更“深度”的选择，举例：影响到子组件，可以使用 `:deep()` 这个伪类：
```

2021-08-17 02:48 UTC, wxsms commented on src/api/sfc-style.md
> +默认情况下，作用域样式不会影响到 `<slot/>` 渲染出来的内容，因为它们被认为是父组件所持有并传递进来的。想要确切的将插槽内容作为选择器的目标，使用 `:slotted` 伪类：
```suggestion
默认情况下，作用域样式不会影响到 `<slot/>` 渲染出来的内容，因为它们被认为是父组件所持有并传递进来的。使用 `:slotted` 伪类以确切地将插槽内容作为选择器的目标：
```

2021-08-17 02:48 UTC, wxsms commented on src/api/sfc-style.md
> +如果你只想让一个样式规则应用到全局，比起另外创建一个 `<style>`，你可以使用 `:global` 伪类来实现 (看下面代码)：
```suggestion
如果想让其中一个样式规则应用到全局，比起另外创建一个 `<style>`，可以使用 `:global` 伪类来实现 (看下面的代码)：
```

2021-08-17 02:48 UTC, wxsms commented on src/api/sfc-style.md
> +- **作用域样式并没有消除对 CSS 类的需求**。由于浏览器渲染渲染各种各样 CSS 选择器的方式，`p { color: red }` 会比使用作用域样式的时候慢几倍 (也即当与属性选择器组合使用的时候)。如果你使用 class 或者 id 来替代，例如 `.example { color: red }`，那你事实上已经消除了这个性能提示。
```suggestion
- **作用域样式并没有消除对 CSS 类的需求**。由于浏览器渲染渲染各种各样 CSS 选择器的方式，`p { color: red }` 结合作用域样式使用时会慢很多倍 (也即当与属性选择器组合使用的时候)。如果使用 class 或者 id 来替代，例如 `.example { color: red }`，那你事实上避免了这个性能损失。
```

2021-08-17 02:48 UTC, wxsms commented on src/api/sfc-style.md
> +参考 [CSS Modules spec](https://github.com/css-modules/css-modules) 文档查看模式详情，例如 [global exceptions](https://github.com/css-modules/css-modules#exceptions) 和 [composition](https://github.com/css-modules
```suggestion
参考 [CSS Modules 规范](https://github.com/css-modules/css-modules) 以查看更多详情，例如 [global exceptions](https://github.com/css-modules/css-modules#exceptions) 和 [composition](https://github.com/css-modules/css-modules#composition)。
```

原文的 mode 应该是个 typo，我给原文发起了一个PR：https://github.com/vuejs/docs/pull/1186

2021-08-17 02:48 UTC, wxsms commented on src/api/sfc-style.md
> +### 与 Composition API 一同使用
```suggestion
### 与组合式 API 一同使用
```

2021-08-17 03:23 UTC, arronKler commented on src/api/sfc-style.md
> +参考 [CSS Modules spec](https://github.com/css-modules/css-modules) 文档查看模式详情，例如 [global exceptions](https://github.com/css-modules/css-modules#exceptions) 和 [composition](https://github.com/css-modules
我说咋看起来不对。。

2021-08-17 03:26 UTC, arronKler commented on src/api/sfc-style.md
> +如果你想要在 `scoped` 的样式里的选择器能做更“深度”的选择，也即：影响到子组件，你可以使用 `:deep()` 这个伪类：
i.e 的意思是 ”换句话说“，”那就是说“。 e.g 才是表示 ”举例“ 。 https://www.hopenglish.com/hope-tips-i-e-vs-e-g

2021-08-17 03:27 UTC, arronKler commented on src/api/sfc-style.md
> +当 `<style>` 标签有 `scoped` 特性的时候，它的 CSS 只会应用到当前组件的元素上。这类似于 Shadow DOM 中的样式封装。它带有一些警告，但是并不需要任何的 polyfill。它是通过 PostCSS 转换以下内容来实现的：
Get

2021-08-17 03:28 UTC, wxsms commented on src/api/sfc-style.md
> +如果你想要在 `scoped` 的样式里的选择器能做更“深度”的选择，也即：影响到子组件，你可以使用 `:deep()` 这个伪类：
噢，好的，学习了。

2021-08-19 02:13 UTC, veaba requested changes
关于`property` 与 `attribute` 的其他场景下，详见 wiki

2021-08-19 02:13 UTC, veaba commented on src/api/sfc-style.md
> +您可以通过给 `module` 属性一个值来自定义注入的 class 对象的属性键：
除了计算属性外，关于`property` 与 `attribute` 的其他场景下，我们有约定，保留原文，详见 wiki。

下同。

2021-08-19 05:51 UTC, arronKler commented on src/api/sfc-style.md
> +您可以通过给 `module` 属性一个值来自定义注入的 class 对象的属性键：
got it

2021-08-19 07:16 UTC, veaba requested changes

2021-08-19 07:16 UTC, veaba commented on src/api/sfc-style.md
> +您可以通过给 `module` attribute 一个值来自定义注入的 class 对象的 property 键：
```suggestion
你可以通过给 `module` attribute 一个值来自定义注入的类对象的 property 键：
```

2021-08-19 07:16 UTC, veaba commented on src/api/sfc-style.md
> +这个语法同样也适用于 [`<script setup>`](./sfc-script-setup)，且支持 Javascript 表达式 (需要用引号包裹起来)
```suggestion
这个语法同样也适用于 [`<script setup>`](./sfc-script-setup)，且支持 JavaScript 表达式 (需要用引号包裹起来)
```

2021-08-19 07:16 UTC, veaba commented on src/api/sfc-style.md
> +实际的值会被编译成散列的 CSS 自定义 property，CSS 本身仍然是静态的。自定义 property 会通过内联样式的方式应用到组件的根元素上，并且在源值变更的时候响应式更新。
```suggestion
实际的值会被编译成 hash 的 CSS 自定义 property，CSS 本身仍然是静态的。自定义 property 会通过内联样式的方式应用到组件的根元素上，并且在源值变更的时候响应式更新。
```

2021-08-19 08:33 UTC, arronKler commented on src/api/sfc-style.md
> +对生成的类进行散列以避免冲突，实现了将 CSS 仅作用于当前组件的相同效果。
```suggestion
对生成的类做 hash 计算以避免冲突，实现了和 scope CSS 一样将 CSS 仅作用于当前组件的效果。
```
稍微调整了一下，后面部分也重新翻译了一下

2021-08-19 09:46 UTC, veaba approved these changes

2021-08-19 09:49 UTC, merged