Fix:Undate options-lifecycle-hooks
vuejs/docs-next-zh-cn pull request #666
Opened 2021-08-19 18:19 UTC by Yukon123

## Description of Problem

修正了生命周期钩子api的错误描述  并且优化了些里面的描述

## Proposed Solution
参照英文文档进行比对校验,有错的进行了修复.

 https://v3.vuejs.org/api/options-lifecycle-hooks.html#lifecycle-hooks

## Additional Information

欢迎进行评论指正.谢谢!

2021-08-20 01:34 UTC, wxsms requested changes

2021-08-20 01:34 UTC, wxsms commented on src/api/options-lifecycle-hooks.md
> +所有的生命周期钩子自动绑定 `this` 上下文到实例中，因此你可以访问 data ，computed properties (计算属性)和 methods 。这意味着**你不应该使用箭头函数来定义一个生命周期方法** (例如 `created: () => this.fetchTodos()`) 。因为箭头函数绑定了父级上下文，因此 `this` 不会指向预期的组件实例，并且`this.fet
```suggestion
所有生命周期钩子的 `this` 上下文将自动绑定至实例中，因此你可以访问 data，computed property (计算属性) 和 methods 。这意味着**你不应该使用箭头函数来定义一个生命周期方法** (例如 `created: () => this.fetchTodos()`) 。因为箭头函数绑定了父级上下文，所以 `this` 不会指向预期的组件实例，并且`this.fetchTodos` 将会是 undefined。
```

2021-08-20 01:34 UTC, wxsms commented on src/api/options-lifecycle-hooks.md
> +  在实例初始化之后被立刻调用，随后进行data observation (数据观测) 和 event/watcher (事件/侦听器)的配置 。
```suggestion
  在实例初始化之后，data observation (数据观测) 和 event/watcher (事件/侦听器) 配置之前被立即同步调用。
```

这里我觉得原翻译的语序更好一些。另外原文有一个 `synchronously` 没有被体现。

2021-08-20 01:34 UTC, wxsms commented on src/api/options-lifecycle-hooks.md
> +  在实例创建完成后被立即调用。在这一步，实例已完成以下的配置：data observation(数据观测)，computed properties(计算属性),methods，event/watcher (事件/侦听器)的回调函数。然而，挂载阶段还没开始，`$el` property 目前尚不可用。
```suggestion
  在实例创建完成后被立即同步调用。在这一步中，实例已完成对选项的处理，意味着以下内容已被配置完毕：data observation (数据观测)，computed property (计算属性)，methods，event/watcher (事件/侦听器) 的回调函数。然而，挂载阶段还没开始，且 `$el` property 目前尚不可用。
```

2021-08-20 01:34 UTC, wxsms commented on src/api/options-lifecycle-hooks.md
> +  在实例挂载完成后被调用，这时候传递给 [`app.mount`](/api/application-api.html#mount)的元素`el`被新创建的 `vm.$el` 替换了。如果根实例挂载到一个文档内的元素上，当 `mounted` 被调用时 `vm.$el` 也在文档内。
```suggestion
  在实例挂载完成后被调用，这时候传递给 [`app.mount`](/api/application-api.html#mount) 的元素已经被新创建的 `vm.$el` 替换了。如果根实例被挂载到了一个文档内的元素上，当 `mounted` 被调用时， `vm.$el` 也会在文档内。
```

原文貌似并没有 `el` 的描述？

2021-08-20 01:34 UTC, wxsms commented on src/api/options-lifecycle-hooks.md
> +  注意 `mounted` **不会**保证所有的子组件也都被挂载完成。如果你希望等到整个视图都渲染完毕再执行某些操作，可以在 `mounted` 内部使用 [vm.$nextTick](../api/instance-methods.html#nexttick)：
```suggestion
  注意 `mounted` **不会**保证所有的子组件也都被挂载完成。如果你希望等待整个视图都渲染完毕，可以在 `mounted` 内部使用 [vm.$nextTick](../api/instance-methods.html#nexttick)：
```

2021-08-20 01:34 UTC, wxsms commented on src/api/options-lifecycle-hooks.md
> +- **详细：**
```suggestion
- **详细：**
```

多了一个空格

2021-08-20 01:34 UTC, wxsms commented on src/api/options-lifecycle-hooks.md
> +  在数据发生改变时被调用，发生在 DOM 更新之前。这里适合在更新之前访问现有的 DOM，比如移除手动添加的事件监听器。
```suggestion
  在数据发生改变后，DOM 被更新之前被调用。这里适合在现有 DOM 被更新之前访问它，比如移除手动添加的事件监听器。
```

2021-08-20 01:34 UTC, wxsms commented on src/api/options-lifecycle-hooks.md
> +  在数据更改导致虚拟 DOM 重新渲染完毕和更新后被调用。
```suggestion
  在数据更改导致的虚拟 DOM 重新渲染和更新完毕之后被调用。
```

2021-08-20 01:34 UTC, wxsms commented on src/api/options-lifecycle-hooks.md
> +  注意，`updated` **不会**保证所有的子组件也都被重新渲染完毕。如果你希望等到整个视图都渲染完毕再执行某些操作，可以在 `updated` 里使用 [vm.$nextTick](../api/instance-methods.html#nexttick)：
```suggestion
  注意，`updated` **不会**保证所有的子组件也都被重新渲染完毕。如果你希望等待整个视图都渲染完毕，可以在 `updated` 内部使用 [vm.$nextTick](../api/instance-methods.html#nexttick)：
```

跟上面的 mounted 一样，此处原文貌似没有 `再执行某些操作` 的描述，另外某些表述可以跟 mounted 保持一致。

2021-08-20 01:50 UTC, Yukon123 commented on src/api/options-lifecycle-hooks.md
> +  在实例初始化之后被立刻调用，随后进行data observation (数据观测) 和 event/watcher (事件/侦听器)的配置 。
我也觉得是被同步调用,考虑到可能会给人有点迷惑  因而删掉了同步的表述.原因是生命钩子本身就是一个effect,在源码中
>       with 'pre' option, the first call must happen before the component is mounted so it is called synchronously.
就是初始化时,created  beforeCreat 和setup选项中的DOM改变都是同步进行的,并不会进入任务队列进行缓冲.
这是我第一版本的翻译:你看看
在实例初始化之后立刻被同步调用，随后进行data observation (数据观测) 和 event/watcher (事件/侦听器)的配置.

2021-08-20 01:52 UTC, Yukon123 commented on src/api/options-lifecycle-hooks.md
> +  在实例初始化之后被立刻调用，随后进行data observation (数据观测) 和 event/watcher (事件/侦听器)的配置 。
我强调`调用`的语序提前主要是`调用`这个词是动词,一句句子太长会让人忽略掉关键词`调用`,也与其他的钩子函数语序保持一致

2021-08-20 01:55 UTC, Yukon123 commented on src/api/options-lifecycle-hooks.md
> +  注意 `mounted` **不会**保证所有的子组件也都被挂载完成。如果你希望等到整个视图都渲染完毕再执行某些操作，可以在 `mounted` 内部使用 [vm.$nextTick](../api/instance-methods.html#nexttick)：
vm.$nextTick 这个property的作用是等到下一次DOM更新后立刻调用,添加`再执行某些操作`会更让人容易理解nextTick的作用.目的是为了在这之后执行操作,而不是为了等待它渲染完毕.

2021-08-20 01:58 UTC, Yukon123 commented on src/api/options-lifecycle-hooks.md
> +  在实例挂载完成后被调用，这时候传递给 [`app.mount`](/api/application-api.html#mount)的元素`el`被新创建的 `vm.$el` 替换了。如果根实例挂载到一个文档内的元素上，当 `mounted` 被调用时 `vm.$el` 也在文档内。
where `element`, passed to app.mount is replaced by the newly created vm.$el.

2021-08-20 02:05 UTC, Yukon123 commented on src/api/options-lifecycle-hooks.md
> +  注意，`updated` **不会**保证所有的子组件也都被重新渲染完毕。如果你希望等到整个视图都渲染完毕再执行某些操作，可以在 `updated` 里使用 [vm.$nextTick](../api/instance-methods.html#nexttick)：
关于nextTick,我再想想,我是觉得比较优化表述,免得需要点进后面的连接了解`nexttick`想要做什么,听一下其他人看法.

2021-08-20 02:16 UTC, Yukon123 commented on src/api/options-lifecycle-hooks.md
> +  在实例挂载完成后被调用，这时候传递给 [`app.mount`](/api/application-api.html#mount)的元素`el`被新创建的 `vm.$el` 替换了。如果根实例挂载到一个文档内的元素上，当 `mounted` 被调用时 `vm.$el` 也在文档内。
![image](https://user-images.githubusercontent.com/82578034/130168657-835624e7-39a3-405a-bf75-f20624fff342.png)
在生命周期图示中可以看到

2021-08-20 02:53 UTC, wxsms commented on src/api/options-lifecycle-hooks.md
> +  在实例初始化之后被立刻调用，随后进行data observation (数据观测) 和 event/watcher (事件/侦听器)的配置 。
对此我持有不同意见，我觉得这句话主要强调的是被调用的“时机”。可以等等看其它小伙伴们是什么意见。

2021-08-20 02:57 UTC, wxsms commented on src/api/options-lifecycle-hooks.md
> +  注意 `mounted` **不会**保证所有的子组件也都被挂载完成。如果你希望等到整个视图都渲染完毕再执行某些操作，可以在 `mounted` 内部使用 [vm.$nextTick](../api/instance-methods.html#nexttick)：
你说的是有一定道理，不过翻译嘛应该还是以尊重原文为主比较好。如果觉得表述有优化空间，也许可以去原文提一个建议，被接纳了之后再同步到这里来？

2021-08-20 03:02 UTC, wxsms commented on src/api/options-lifecycle-hooks.md
> +  在实例挂载完成后被调用，这时候传递给 [`app.mount`](/api/application-api.html#mount)的元素`el`被新创建的 `vm.$el` 替换了。如果根实例挂载到一个文档内的元素上，当 `mounted` 被调用时 `vm.$el` 也在文档内。
element passed to `app.mount` > 传递给 `app.mount` 的元素

这里的 element 已经用“元素”翻译了呀，所以是否没有再在后面添加一个 `el` 的必要呢？

2021-08-21 01:38 UTC, Jinjiang commented on src/api/options-lifecycle-hooks.md
> +  在实例初始化之后被立刻调用，随后进行data observation (数据观测) 和 event/watcher (事件/侦听器)的配置 。
我也觉得原文更准确一些，新的译法有点演绎和二次解读的成分在。而且我感觉这样的描述可能会让一些人误以为 data observation 和 event/watcher 是在这个 hook 内部进行的

2021-08-21 02:47 UTC, Justineo requested changes

2021-08-21 02:47 UTC, Justineo commented on src/api/options-lifecycle-hooks.md
> +所有生命周期钩子的 `this` 上下文将自动绑定至实例中，因此你可以访问 data，computed property (计算属性) 和 methods 。这意味着**你不应该使用箭头函数来定义一个生命周期方法** (例如 `created: () => this.fetchTodos()`) 。因为箭头函数绑定了父级上下文，所以 `this` 不会指向预期的组件实例，并且`this.fetc
```suggestion
所有生命周期钩子的 `this` 上下文将自动绑定至实例中，因此你可以访问 data、computed 和 methods。这意味着**你不应该使用箭头函数来定义一个生命周期方法** (例如 `created: () => this.fetchTodos()`) 。因为箭头函数绑定了父级上下文，所以 `this` 不会指向预期的组件实例，并且`this.fetchTodos` 将会是 undefined。
```

这里感觉这几个概念可以都保留英文能更好地进行对应。

2021-08-21 02:47 UTC, Justineo commented on src/api/options-lifecycle-hooks.md
> +  在实例初始化之后被立刻调用，随后进行data observation (数据观测) 和 event/watcher (事件/侦听器)的配置 。
```suggestion
  在实例初始化之后、进行数据侦听和事件/侦听器的配置之前同步调用。
```

这里几处保留原文的大家也可以看一下是不是需要翻译。/cc @Jinjiang @veaba @wxsms

2021-08-21 02:47 UTC, Justineo commented on src/api/options-lifecycle-hooks.md
> +  **该钩子在服务器端渲染期间不被调用，因为只有初次渲染会在服务器端进行。**
这个改动没必要，“服务端”也是常用的说法。

2021-08-21 02:47 UTC, Justineo commented on src/api/options-lifecycle-hooks.md
> +  注意，`updated` **不会**保证所有的子组件也都被重新渲染完毕。如果你希望等到整个视图都渲染完毕再执行某些操作，可以在 `updated` 里使用 [vm.$nextTick](../api/instance-methods.html#nexttick)：
个人觉得不需要加“再执行某些操作”，因为你等待一个时机必然是要再做些什么的。

2021-08-21 07:17 UTC, Yukon123 commented on src/api/options-lifecycle-hooks.md
> +  在实例初始化之后被立刻调用，随后进行data observation (数据观测) 和 event/watcher (事件/侦听器)的配置 。
好的

2021-08-21 08:46 UTC, wxsms commented on src/api/options-lifecycle-hooks.md
> +  在实例初始化之后被立刻调用，随后进行data observation (数据观测) 和 event/watcher (事件/侦听器)的配置 。
个人觉得这里还是保留原文比较好，原因是像 data / watch / method 这些词，它除了表达那层意思以外，同时也是 options api 的关键字，保留英文可以让对应关系更明显。

至于形式，对比了一下，还是觉得原本的翻译形式 `数据观测 (data observer)  `，即中文在前，括号内保留原文的形式更为合适。

2021-08-21 16:46 UTC, Yukon123 commented on src/api/options-lifecycle-hooks.md
> +  在实例初始化之后被立刻调用，随后进行data observation (数据观测) 和 event/watcher (事件/侦听器)的配置 。
在实例初始化之后、进行数据 (data) 观测和事件/侦听器的配置之前同步调用。  这样怎么样?

2021-08-21 18:51 UTC, Yukon123 commented on src/api/options-lifecycle-hooks.md
> +  在实例初始化之后被立刻调用，随后进行data observation (数据观测) 和 event/watcher (事件/侦听器)的配置 。
目前改成这样: 在实例初始化之后,进行数据侦听和事件/侦听器的配置之前同步调用。

2021-08-24 14:46 UTC, Yukon123 commented on src/api/options-lifecycle-hooks.md
> +  在实例初始化之后被立刻调用，随后进行data observation (数据观测) 和 event/watcher (事件/侦听器)的配置 。
@Justineo @Jinjiang @wxsms 您好,已修改.感觉可以合并上去了吧.

2021-08-29 03:05 UTC, Jinjiang commented on src/api/options-lifecycle-hooks.md
> +所有生命周期钩子的 `this` 上下文将自动绑定至实例中，因此你可以访问 data、computed 和 methods。这意味着**你不应该使用箭头函数来定义一个生命周期方法** (例如 `created: () => this.fetchTodos()`) 。因为箭头函数绑定了父级上下文，所以 `this` 不会指向预期的组件实例，并且`this.fetchTodos` 将会是 undef
```suggestion
所有生命周期钩子的 `this` 上下文将自动绑定至实例中，因此你可以访问 data、computed 和 methods。这意味着**你不应该使用箭头函数来定义一个生命周期方法** (例如 `created: () => this.fetchTodos()`)。因为箭头函数绑定了父级上下文，所以 `this` 不会指向预期的组件实例，并且`this.fetchTodos` 将会是 undefined。
```

2021-08-29 03:05 UTC, Jinjiang commented on src/api/options-lifecycle-hooks.md
> +  在实例初始化之后被立刻调用，随后进行data observation (数据观测) 和 event/watcher (事件/侦听器)的配置 。
目前这几个名词在其它地方都已经被翻译了，我觉得保持一致比较好。

2021-08-29 03:20 UTC, Jinjiang reviewed
在之前的讨论基础上稍微多解释一下我为什么倾向于直接使用中文翻译，尤其是原文的“which means the following have been set up: data observation, computed properties, methods, watch/event callbacks”这部分。因为原文并没有用反引号注明这里是特指 API 名称，所以我倾向于用最直白的中文翻译来描述，包括 methods 我译为了方法。同时这里的翻译不会产生歧义或不准确，因为在这个 set up 的语境下，没有其它的可能，只可能是组件选项。第三虽然 observation 和 watcher 在英文里是不同单词，但这里其实都是侦听的意思，所以翻译成相同的中文也是没有问题的，我们的 wiki 里也是这样约定的。

如果这个点上仍有争议，我们可以单独开一个 issue 讨论，因为这份 PR 整体上是没有问题的，我们可以先让其它部分生效。

2021-08-29 03:20 UTC, Jinjiang commented on src/api/options-lifecycle-hooks.md
> +  在实例初始化之后,进行数据侦听和事件/侦听器的配置之前同步调用。
```suggestion
  在实例初始化之后、进行数据侦听和事件/侦听器的配置之前同步调用。
```

2021-08-29 03:20 UTC, Jinjiang commented on src/api/options-lifecycle-hooks.md
> +  在实例创建完成后被立即同步调用。在这一步中，实例已完成对选项的处理，意味着以下内容已被配置完毕：data observation (数据观测)，computed property (计算属性)，methods，event/watcher (事件/侦听器) 的回调函数。然而，挂载阶段还没开始，且 `$el` property 目前尚不可用。
```suggestion
  在实例创建完成后被立即同步调用。在这一步中，实例已完成对选项的处理，意味着以下内容已被配置完毕：数据侦听、计算属性、方法、事件/侦听器的回调函数。然而，挂载阶段还没开始，且 `$el` property 目前尚不可用。
```

2021-08-29 03:20 UTC, Jinjiang commented on src/api/options-lifecycle-hooks.md
> +  - 如果一个组件的 inheritance chain (继承链)或 parent chain (父链)中存在多个 `errorCaptured` 钩子，则它们将会被相同的错误逐个唤起。
```suggestion
  - 如果一个组件的继承链或父级链中存在多个 `errorCaptured` 钩子，则它们将会被相同的错误逐个唤起。
```

2021-08-29 03:26 UTC, merged