docs: translated api/sfc-spec.md
vuejs/docs-next-zh-cn pull request #667
Opened 2021-08-20 06:59 UTC by arronKler

Translated api/sfc-spec.md file.

Request for review.

2021-08-23 10:14 UTC, wxsms requested changes

2021-08-23 10:14 UTC, wxsms commented on src/api/sfc-spec.md
> +为了满足任何项目的特定需要，`*.vue` 文件中可以包含额外的自定义块，例如 `<docs>` 块。一些真实场景的自定义块案例包括：
```suggestion
为了满足任何的项目特定需求，`*.vue` 文件中可以包含额外的自定义块，例如 `<docs>` 块。自定义块的一些真实场景的案例包括：
```

2021-08-23 10:14 UTC, wxsms commented on src/api/sfc-spec.md
> +- [Gridsome：`<page-query>`](https://gridsome.org/docs/querying-data/)
```suggestion
- [Gridsome: `<page-query>`](https://gridsome.org/docs/querying-data/)
```

此处的冒号应该没有必要替换吧，上下文都是英文，下同

2021-08-23 10:14 UTC, wxsms commented on src/api/sfc-spec.md
> +- [vite-plugin-vue-gql：`<gql>`](https://github.com/wheatjs/vite-plugin-vue-gql)
```suggestion
- [vite-plugin-vue-gql: `<gql>`](https://github.com/wheatjs/vite-plugin-vue-gql)
```

2021-08-23 10:14 UTC, wxsms commented on src/api/sfc-spec.md
> +- [vue-i18n：`<i18n>`](https://github.com/intlify/bundle-tools/tree/main/packages/vite-plugin-vue-i18n#i18n-custom-block)
```suggestion
- [vue-i18n: `<i18n>`](https://github.com/intlify/bundle-tools/tree/main/packages/vite-plugin-vue-i18n#i18n-custom-block)
```

2021-08-23 10:14 UTC, wxsms commented on src/api/sfc-spec.md
> +对 Custom Block 的处理依赖于工具。如果你想要构建你自己的自定义块集成，更多详情请查看 [SFC 工具](/api/sfc-tooling.html#custom-blocks-integration)。
```suggestion
对 Custom Block 的处理依赖于工具——如果你想要构建自己的自定义块集成，更多详情请查看 [SFC 工具](/api/sfc-tooling.html#custom-blocks-integration)。
```

这里可以保留破折号

2021-08-23 10:14 UTC, wxsms commented on src/api/sfc-spec.md
> +- 开发环境格式化警告
```suggestion
- 开发环境警告格式化
```

2021-08-23 10:14 UTC, wxsms commented on src/api/sfc-spec.md
> +快可以使用 `lang` attribute 声明预处理语言。最常见的场景就是在 `<script>` 块中使用 TypeScript：
```suggestion
块可以使用 `lang` attribute 声明预处理语言。最常见的场景就是在 `<script>` 块中使用 TypeScript：
```

2021-08-23 10:14 UTC, wxsms commented on src/api/sfc-spec.md
> +`lang` 可以用于任何块，例如可以在 `<style>` 里使用 [SASS](https://sass-lang.com/) 以及在 `<template>` 里使用 [Pug](https://pugjs.org/api/getting-started.html)：
```suggestion
`lang` 可以用于任何块——例如可以在 `<style>` 中使用 [SASS](https://sass-lang.com/) 以及在 `<template>` 中使用 [Pug](https://pugjs.org/api/getting-started.html)：
```

2021-08-23 10:14 UTC, wxsms commented on src/api/sfc-spec.md
> +注意，基于不同的工具链，预处理器的集成方式有所不同。检视对应的文档，例如：
```suggestion
注意，基于不同的工具链，预处理器的集成方式有所不同。具体例子请检视对应的文档：
```

2021-08-23 10:14 UTC, wxsms commented on src/api/sfc-spec.md
> +注意 `src` imports 需要遵循和 webpack 模块所要求的同样的路径解析规则，也即：
```suggestion
注意 `src` 引入所需遵循的路径解析规则与 webpack 模块一致，也即：
```

2021-08-23 10:14 UTC, wxsms commented on src/api/sfc-spec.md
> +<!-- 从安装完成的 "todomvc-app-css" npm 包中引入文件 -->
```suggestion
<!-- 从安装好的 "todomvc-app-css" npm 包中引入文件 -->
```

2021-08-23 10:14 UTC, wxsms commented on src/api/sfc-spec.md
> +`src` imports 在自定义块上也一样生效，例如：
```suggestion
`src` 引入也能用于自定义块，例如：
```

2021-08-23 10:14 UTC, wxsms commented on src/api/sfc-spec.md
> +每个块中你应该使用被用到的语言的注释语法。对于顶层的注释，使用 HTML 注释语法：`<!-- comment contents here -->`。
```suggestion
在每个块中，注释应该使用相应语言 (HTML, CSS, JavaScript, Pug, 等等) 的语法。对于顶层的注释而言，使用 HTML 注释语法：`<!-- comment contents here -->`。
```

这里感觉翻译过来不太对通顺，对原文稍微做了一些调整，也不知道好不好。

2021-08-24 02:57 UTC, arronKler commented on src/api/sfc-spec.md
> +- script 会被预处理并作为组件的 `setup()` 函数，也就是说它会在**每个组件实例**中执行。`<script setup>` 的顶层绑定会自动暴露给模板。更多详情请查看 [`<script setup>` 专项文件](/api/sfc-script-setup)。
恩，直观一点，`<script setup>` 本身就是特指，省略应该也是可以的

2021-08-24 03:04 UTC, arronKler commented on src/api/sfc-spec.md
>  ## Src Imports
```suggestion
## Src 引入
```

2021-08-29 03:01 UTC, Jinjiang commented on src/api/sfc-spec.md
> +在每个块中，注释应该使用相应语言 (HTML, CSS, JavaScript, Pug, 等等) 的语法。对于顶层的注释而言，使用 HTML 注释语法：`<!-- comment contents here -->`。
```suggestion
在每个块中，注释应该使用相应语言 (HTML, CSS, JavaScript, Pug, 等等) 的语法。对于顶层的注释而言，使用 HTML 注释语法：`<!-- 这里是注释内容 -->`。
```

2021-08-29 03:21 UTC, merged