Update refs-api.md
vuejs/docs-next-zh-cn pull request #673
Opened 2021-08-21 18:44 UTC by Yukon123

## Description of Problem
- reactive 是个函数 而不是方法   https://github.com/vuejs/docs/pull/1199

-  ` toRefs `  和 ` toRef `  只能用在  **reactive**  对象上  **ref**  对象也是响应式对象

-  解构/展开是 destructure/spread  更精确的称呼

-   effect根据 #657 保留effect本身

2021-08-24 08:10 UTC, wxsms requested changes

2021-08-24 08:10 UTC, wxsms commented on src/api/refs-api.md
> +可以用来为源 reactive 对象上的某个 property 新创建一个 [`ref`](#ref)。然后，ref 可以被传递，它会保持对其源 property 的响应式连接。
这里保留原文的目的是什么呢？wiki 有说明 reactive 应该翻译为响应式。下同。

2021-08-24 08:10 UTC, wxsms commented on src/api/refs-api.md
> +手动执行与 [`shallowRef`](#shallowref) 关联的任何effect。
```suggestion
手动执行与 [`shallowRef`](#shallowref) 关联的任何 effect。
```

2021-08-24 08:10 UTC, wxsms commented on src/api/refs-api.md
> +// 这不会触发effect，因为 ref 是浅层的
```suggestion
// 这不会触发 effect，因为 ref 是浅层的
```

2021-08-24 08:20 UTC, Yukon123 commented on src/api/refs-api.md
> +可以用来为源 reactive 对象上的某个 property 新创建一个 [`ref`](#ref)。然后，ref 可以被传递，它会保持对其源 property 的响应式连接。
[ref](https://v3.vuejs.org/api/refs-api.html#ref) 对象也是 响应式 对象  ref对象不可以使用 `toRef` 和`toRefs`  函数
只有 reactive 对象可以使用  `toRef` 和 `toRefs` 这两个函数
 
下面是ref 函数 在文档中的定义   返回一个可变的响应式的 ref 对象 
>Takes an inner value and returns a reactive and mutable ref object.

2021-09-05 02:51 UTC, Jinjiang commented on src/api/refs-api.md
> +可以用来为源 reactive 对象上的某个 property 新创建一个 [`ref`](#ref)。然后，ref 可以被传递，它会保持对其源 property 的响应式连接。
我觉得这里不是翻译不翻译的问题，首先 reactive 按照约定全部翻译成响应式这个没有疑问。其次，这里的描述我觉得不存在二义性或误解，从翻译的角度我觉得目的已经达到了。至于有没有更好的译法，我愿意持开放态度做后续讨论。截至目前我觉得原译可以保留。

> Takes an inner value and returns a reactive and mutable ref object.

对于 reactive object 和 reactive ref object 的含义，我个人觉得是可以区分的。如果觉得有继续讨论的必要，建议先在英文原版讨论。

2021-09-05 02:54 UTC, Jinjiang commented on src/api/refs-api.md
> +手动执行与 [`shallowRef`](#shallowref) 关联的任何 effect。
effect 需要翻译为作用，参考 wiki。下同

2021-09-05 04:17 UTC, Justineo commented on src/api/refs-api.md
> +手动执行与 [`shallowRef`](#shallowref) 关联的任何 effect。
“作用”感觉太 general 了，我建议是不是除了 side effect -> 副作用这种固定翻译以外，effect 都保留？（当然，是专指的 Vue 语境下的 effect）

2021-09-05 05:16 UTC, Jinjiang commented on src/api/refs-api.md
> +手动执行与 [`shallowRef`](#shallowref) 关联的任何 effect。
Effect 本质上是个函数式编程里的常见词汇，而且是自然语言范畴的描述，所以我个人倾向于翻译而不是保留英文。
回到这句话，也许只是组织语言的问题，比如“手动执行 xxx 的关联作用”

2021-09-05 08:32 UTC, Yukon123 commented on src/api/refs-api.md
> +手动执行与 [`shallowRef`](#shallowref) 关联的任何 effect。
>Vue keeps track of which function is currently running by using an `effect`. An `effec`t is a wrapper around the function that initiates tracking just before the function is called. Vue knows which `effect` is running at any given point and can run it again when required.
[官方文档关于effect的定义](https://v3.vuejs.org/guide/reactivity.html#how-vue-knows-what-code-is-running)
effect 本质上是一个函数的包裹器,也是Vue里面特指的,直接翻译成`作用` 太泛指,不能和响应式原理的effect联系起来.
我也觉得 除了除了 side effect -> 副作用这种固定翻译以外，effect 都应当保留.

2021-09-05 09:16 UTC, Yukon123 commented on src/api/refs-api.md
> +手动执行与 [`shallowRef`](#shallowref) 关联的任何 effect。
我觉得应该和把所有和响应式原理有关的`effect`保留本身,原因就是上文的Vue文档已经对effect进行很清楚的定义.如果简单翻译成作用的话,会把常规的`effect`作用(出现[过渡](https://v3.vuejs.org/guide/migration/transition-as-root.html#migration-strategy)这一章节: A similar `effect` can be achieved by passing a prop to the component instead)和响应式的`effect`函数两者混淆起来,并不能直观地看出`作用`指的是什么.

Vue 源码中 `effect` 也是一个特定的导出的函数,和响应式原理有着非常大的关系.

在中文文档的响应式原理中 把`effect`翻译成副作用和wiki关于副作用的定义有很大落差.翻译成`作用`和普通的`作用`无法区分开,综上建议直接保留`effect`本身.

2021-09-05 14:40 UTC, Justineo commented on src/api/refs-api.md
> +手动执行与 [`shallowRef`](#shallowref) 关联的任何 effect。
React 的文档里面目前我看是保留 effect 原文的。

2021-09-19 05:38 UTC, Jinjiang commented on src/api/refs-api.md
> +手动执行与 [`shallowRef`](#shallowref) 关联的任何 effect。
我目前倾向于同时保留中英文，英文放在括号里作为译注。更多讨论或本 PR 中其它有争议的话题可以单独开 issue。
谢谢

2021-09-19 05:38 UTC, Jinjiang commented on src/api/refs-api.md
> +// 这不会触发 effect，因为 ref 是浅层的
```suggestion
// 这不会触发作用 (effect)，因为 ref 是浅层的
```

2021-09-19 05:38 UTC, Jinjiang commented on src/api/refs-api.md
> +手动执行与 [`shallowRef`](#shallowref) 关联的任何 effect。
```suggestion
手动执行与 [`shallowRef`](#shallowref) 关联的任何作用 (effect)。
```

2021-09-19 05:38 UTC, Jinjiang commented on src/api/refs-api.md
> +当从组合式函数返回 reactive 对象时，`toRefs` 非常有用，这样消费组件就可以在不丢失响应性的情况下对返回的对象进行解构/展开：
```suggestion
当从组合式函数返回响应式对象时，`toRefs` 非常有用，这样消费组件就可以在不丢失响应性的情况下对返回的对象进行解构/展开：
```

2021-09-19 05:38 UTC, Jinjiang commented on src/api/refs-api.md
> +将 reactive 对象转换为普通对象，其中结果对象的每个 property 都是指向原始对象相应 property 的 [`ref`](#ref)。
```suggestion
将响应式对象转换为普通对象，其中结果对象的每个 property 都是指向原始对象相应 property 的 [`ref`](#ref)。
```

2021-09-19 05:38 UTC, Jinjiang commented on src/api/refs-api.md
> +可以用来为源 reactive 对象上的某个 property 新创建一个 [`ref`](#ref)。然后，ref 可以被传递，它会保持对其源 property 的响应式连接。
```suggestion
可以用来源响应式对象上的某个 property 新创建一个 [`ref`](#ref)。然后，ref 可以被传递，它会保持对其源 property 的响应式连接。
```

2021-09-19 05:40 UTC, Jinjiang commented on src/api/refs-api.md
> +可以用来源响应式对象上的某个 property 新创建一个 [`ref`](#ref)。然后，ref 可以被传递，它会保持对其源 property 的响应式连接。
```suggestion
可以用来为源响应式对象上的某个 property 新创建一个 [`ref`](#ref)。然后，ref 可以被传递，它会保持对其源 property 的响应式连接。
```

2021-09-19 05:44 UTC, merged