docs: Update custom-elements-interop.md
vuejs/docs-next-zh-cn pull request #690
Opened 2021-08-31 01:56 UTC by wxsms

## Description of Problem

翻译修缮。

2021-09-04 16:10 UTC, Justineo requested changes

2021-09-04 16:10 UTC, Justineo commented on src/guide/migration/custom-elements-interop.md
>  ## 概览
这篇标题也应该改一下，应该是“与自定义元素的互操作性”。

2021-09-04 16:10 UTC, Justineo commented on src/guide/migration/custom-elements-interop.md
> +- 如果使用构建步骤：将 `isCustomElement` 传递给 Vue 模板编译器，如果使用了 `vue-loader`，则应通过 `vue-loader` 的 `compilerOptions` 选项传递：
```suggestion
- 如果使用构建步骤：给 Vue 模板编译器传入 `isCustomElement` 选项。如果使用了 `vue-loader`，则应通过 `vue-loader` 的 `compilerOptions` 选项传递：
```

2021-09-04 16:10 UTC, Justineo commented on src/guide/migration/custom-elements-interop.md
>  ## `vue:` 用于 DOM 内模板解析解决方案
```suggestion
## 使用 `vue:` 前缀来解决 DOM 内模板解析问题
```

2021-09-05 01:44 UTC, wxsms commented
标题的更改已检查，无需要更新的外部链接。

2021-09-08 11:27 UTC, merged

2021-09-08 11:29 UTC, veaba reviewed
approve