review: sfc-spec
vuejs/docs-next-zh-cn pull request #691
Opened 2021-08-31 01:59 UTC by Ardor-Zhang

review sfc-spec

2021-08-31 02:05 UTC, wxsms requested changes

2021-08-31 02:05 UTC, wxsms commented on src/api/sfc-spec.md
> +- `<style>` 标签可以通过 `scoped` 或 `module` 属性 (更多详情请查看 [SFC 样式特性](/api/sfc-style)) 将样式封装到当前组件。多个不同封装模式的 `<style>` 标签可以在同一个组件中混用。
根据 wiki，attribute 是不翻译的，下同。

2021-08-31 02:44 UTC, Ardor-Zhang commented on src/api/sfc-spec.md
> +- `<style>` 标签可以通过 `scoped` 或 `module` 属性 (更多详情请查看 [SFC 样式特性](/api/sfc-style)) 将样式封装到当前组件。多个不同封装模式的 `<style>` 标签可以在同一个组件中混用。
感谢

2021-09-04 16:14 UTC, Justineo requested changes

2021-09-04 16:14 UTC, Justineo commented on src/api/sfc-spec.md
> +## 语法块
语言块没有问题吧？

2021-09-04 16:14 UTC, Justineo commented on src/api/sfc-spec.md
> +- `<style>` 标签可以通过 `scoped` 或 `module` attribute (更多详情请查看 [SFC 样式特性](/api/sfc-style)) 将样式封装到当前组件。多个不同封装模式的 `<style>` 标签可以在同一个组件中混用。
```suggestion
- `<style>` 标签可以通过 `scoped` 或 `module` attribute (更多详情请查看 [SFC 样式特性](/api/sfc-style)) 将样式封装在当前组件内。多个不同封装模式的 `<style>` 标签可以在同一个组件中混用。
```

2021-09-04 16:14 UTC, Justineo commented on src/api/sfc-spec.md
> +`lang` 可以用于任何块 —— 例如可以在 `<style>` 中使用 [SASS](https://sass-lang.com/) 以及在 `<template>` 中使用 [Pug](https://pugjs.org/api/getting-started.html)：
破折号不需要加空格

```suggestion
`lang` 可以用于任何块 —— 例如可以在 `<style>` 中使用 [Sass](https://sass-lang.com/) 以及在 `<template>` 中使用 [Pug](https://pugjs.org/api/getting-started.html)：
```

2021-09-19 05:50 UTC, Jinjiang commented on src/api/sfc-spec.md
> +## 语法块
```suggestion
## 语言块
```

支持原译，语法在这里不够准确

2021-09-19 05:51 UTC, Jinjiang approved these changes

2021-09-19 05:57 UTC, merged