docs: update reactivity-computed-watchers.md
vuejs/docs-next-zh-cn pull request #692
Opened 2021-08-31 04:09 UTC by richardo2016

## Description of Problem

First translate for section Computing Debugging

## Proposed Solution

None

## Additional Information

None

2021-09-01 06:08 UTC, wxsms requested changes

2021-09-01 06:08 UTC, wxsms commented on src/guide/reactivity-computed-watchers.md
> +- 如果某个反应式属性或 [ref](reactivity-fundamentals.html#创建独立的响应式值作为-refs) 作为依赖被追踪, 则 `onTrack` 会被调用.
```suggestion
- `onTrack`  会在某个响应式属性或 ref 作为依赖被追踪时调用。
```

原文没有为 ref 加链接。

2021-09-01 06:08 UTC, wxsms commented on src/guide/reactivity-computed-watchers.md
> +- 如果 computed 的某个依赖修改, 则 `onTrigger` 会被调用.
```suggestion
- `onTrigger` 会在侦听回调被某个依赖的修改触发时调用。 
```

2021-09-01 06:08 UTC, wxsms commented on src/guide/reactivity-computed-watchers.md
> +这两个回调都会收到一个 debugger 事件, 事件中包含了有关依赖的一些信息. 推荐的用法是, 在这两个回调内放置一个 `debugger` 语句, 用以调试依赖.
```suggestion
所有回调都会收到一个 debugger 事件，其中包含了一些依赖相关的信息。推荐在这些回调内放置一个 `debugger` 语句以调试依赖。
```

标点要使用中文的。
标点需要换成中文的。

2021-09-01 06:08 UTC, wxsms commented on src/guide/reactivity-computed-watchers.md
> +    // 当 count.value 作为依赖被追踪时, 该回调被触发
```suggestion
    // 当 count.value 作为依赖被追踪时触发
```

2021-09-01 06:08 UTC, wxsms commented on src/guide/reactivity-computed-watchers.md
> +    // 当 count.value 被修改时, 该回调被触发
```suggestion
    // 当 count.value 被修改时触发
```

2021-09-01 06:08 UTC, wxsms commented on src/guide/reactivity-computed-watchers.md
> +// 访问 plusOne, 应该触发 onTrack
```suggestion
// 访问 plusOne，应该触发 onTrack
```

2021-09-01 06:08 UTC, wxsms commented on src/guide/reactivity-computed-watchers.md
> +// 修改了 count.value, 应该触发 onTrigger
```suggestion
// 修改 count.value，应该触发 onTrigger
```

2021-09-05 03:06 UTC, Jinjiang commented on src/guide/reactivity-computed-watchers.md
> +你可以给 `computed` 传入一个对象作为第二个参数, 该参数支持 `onTrack` 和 `onTrigger` 选项:
```suggestion
`computed` 可接受一个带有 `onTrack` 和 `onTrigger` 选项的对象作为第二个参数：
```

2021-09-05 03:06 UTC, Jinjiang commented on src/guide/reactivity-computed-watchers.md
> +- 如果某个反应式属性或 [ref](reactivity-fundamentals.html#创建独立的响应式值作为-refs) 作为依赖被追踪, 则 `onTrack` 会被调用.
```suggestion
- `onTrack` 会在某个响应式 property 或 ref 作为依赖被追踪时调用。
```

2021-09-05 03:06 UTC, Jinjiang commented on src/guide/reactivity-computed-watchers.md
> +`onTrack` 和 `onTrigger` 仅在 development 模式下生效.
```suggestion
`onTrack` 和 `onTrigger` 仅在开发模式下生效。
```

2021-09-05 03:10 UTC, merged