Translating security part
vuejs/docs-next-zh-cn pull request #695
Opened 2021-08-31 16:19 UTC by shijiezhou1

Translating security part

## Description of Problem

## Proposed Solution

## Additional Information

2021-09-01 06:15 UTC, wxsms requested changes

2021-09-01 06:15 UTC, wxsms commented on src/guide/security.md
> +## 漏洞报告
```suggestion
## 报告漏洞
```

2021-09-01 06:15 UTC, wxsms commented on src/guide/security.md
> +当一个漏洞被报告时，它立即成为我们最关心的问题，全职贡献者放下一切来处理它。要报告漏洞，请发送电子邮件至 [security@vuejs.org](mailto:security@vuejs.org)。
```suggestion
当一个漏洞被报告时，它将立即成为我们最关心的问题，全职贡献者将放下一切来处理它。要报告漏洞，请发送电子邮件至 [security@vuejs.org](mailto:security@vuejs.org)。
```

2021-09-01 06:15 UTC, wxsms commented on src/guide/security.md
> +虽然很少发现新漏洞，但我们也建议始终使用最新版本的 Vue 及其官方配套库，以确保您的应用程序尽可能安全。
```suggestion
虽然新的漏洞很少被发现，但我们也建议始终使用最新版本的 Vue 及其官方配套库，以确保您的应用尽可能地安全。
```

2021-09-02 07:58 UTC, shijiezhou1 commented
All the commit message changes.

2021-09-02 08:18 UTC, wxsms approved these changes

2021-09-05 03:10 UTC, merged