Fix two origin comments
vuejs/docs-next-zh-cn pull request #720
Opened 2021-09-10 16:41 UTC by Cnotech

修补代码段中两处未翻译的注释

2021-09-11 03:34 UTC, wxsms requested changes

2021-09-11 03:34 UTC, wxsms commented on src/guide/render-function.md
> +      {}, // props或attributes
```suggestion
      {}, // props 或 attributes
```

2021-09-11 18:01 UTC, Cnotech commented on src/guide/render-function.md
> +      {}, // props或attributes
英文版那边保留的s，估计是指可以传入多个参数吧。我觉得可以把s留着或者使用"数个"前缀 xD

2021-09-12 03:25 UTC, Jinjiang commented on src/guide/mixins.md
> +// 定义一个使用此 mixin 对象的 app
```suggestion
// 定义一个使用此 mixin 对象的应用
```

2021-09-12 03:25 UTC, Jinjiang commented on src/guide/render-function.md
> +      {}, // props或attributes
中文翻译统一使用单数，参见我们的翻译须知

2021-09-12 04:03 UTC, merged