translate introduction.md
vuejs/docs-next-zh-cn pull request #781
Opened 2021-10-30 11:58 UTC by wxsms

## Description of Problem

补上了部分翻译。

2021-10-30 13:06 UTC, watonyweng approved these changes

2021-11-01 04:24 UTC, Justineo requested changes

2021-11-01 04:24 UTC, Justineo commented on src/guide/ssr/introduction.md
> +在应用中使用 SSR 之前，你需要问自己的第一个问题是：你是否真的需要它。它通常是由内容呈现时间对应用的重要程度决定的。例如，如果你正在搭建一个内部管理系统，几百毫秒的初始化加载时间对它来说无关紧要，这种情况下就没有必要使用 SSR。然而，如果内容呈现时间非常关键，SSR 可以助你实现最佳的初始加载性能。
```suggestion
在应用中使用 SSR 之前，你需要问自己的第一个问题是：你是否真的需要它？它通常是由内容呈现时间对应用的重要程度决定的。例如，如果你正在搭建一个内部管理系统，几百毫秒的初始化加载时间对它来说无关紧要，这种情况下就没有必要使用 SSR。然而，如果内容呈现时间非常关键，SSR 可以助你实现最佳的初始加载性能。
```

2021-11-01 04:24 UTC, Justineo commented on src/guide/ssr/introduction.md
> +如果你仅希望通过 SSR 来改善一些推广页面(例如 `/`、`/about`、`/contact` 等)的 SEO，那么**预渲染**也许会更合适。和使用动态编译 HTML 的 web 服务器相比，预渲染可以在构建时为指定的路由生成静态 HTML 文件。它的优势在于预渲染的设置更加简单，且允许将前端保持为一个完全静态的站点。
```suggestion
如果你仅希望通过 SSR 来改善一些推广页面 (例如 `/`、`/about`、`/contact` 等) 的 SEO，那么**预渲染**也许会更合适。和使用动态编译 HTML 的 web 服务器相比，预渲染可以在构建时为指定的路由生成静态 HTML 文件。它的优势在于预渲染的设置更加简单，且允许将前端保持为一个完全静态的站点。
```

2021-11-01 04:24 UTC, Justineo commented on src/guide/ssr/introduction.md
> +如果你更倾向于高层级的、提供顺滑的开箱即用体验的解决方案，也许可以试试 [Nuxt.js](https://nuxtjs.org/)。它使用相同的 Vue 技术栈构建，但将许多引用抽象化了，且提供了一些额外的特性，例如静态站点生成。然而，如果你需要对应用的结构有更直接的控制，它也许就不适合了。无论如何，通读本指南，更好地理解事物之间是如何协同工作的，仍然是有益的。
我想可能这一段原文是故意注释掉的，因为之前 Nuxt 还没有 Vue 3 的支持。现在 Nuxt 3 beta 发布了应该可以加上这段描述了，不过可能应该把链接给改成 https://v3.nuxtjs.org/。

2021-11-01 04:35 UTC, wxsms commented on src/guide/ssr/introduction.md
> +如果你更倾向于高层级的、提供顺滑的开箱即用体验的解决方案，也许可以试试 [Nuxt.js](https://nuxtjs.org/)。它使用相同的 Vue 技术栈构建，但将许多引用抽象化了，且提供了一些额外的特性，例如静态站点生成。然而，如果你需要对应用的结构有更直接的控制，它也许就不适合了。无论如何，通读本指南，更好地理解事物之间是如何协同工作的，仍然是有益的。
vuejs/docs#1306

确实是故意注释掉的，这个PR里面有讨论。不过它从一开始就有显示出来到页面上，并且这个PR已经被合并了。所以如果后续要改链接或者重新注释掉是否可以再看英文版那边的意思？

2021-11-01 04:36 UTC, Justineo commented on src/guide/ssr/introduction.md
> +如果你更倾向于高层级的、提供顺滑的开箱即用体验的解决方案，也许可以试试 [Nuxt.js](https://nuxtjs.org/)。它使用相同的 Vue 技术栈构建，但将许多引用抽象化了，且提供了一些额外的特性，例如静态站点生成。然而，如果你需要对应用的结构有更直接的控制，它也许就不适合了。无论如何，通读本指南，更好地理解事物之间是如何协同工作的，仍然是有益的。
OK

2021-11-01 04:36 UTC, merged