update transitions-overview.md
vuejs/docs-next-zh-cn pull request #827
Opened 2021-11-30 03:06 UTC by wxsms

## Description of Problem

翻译修缮

2021-12-04 17:15 UTC, Justineo requested changes

2021-12-04 17:15 UTC, Justineo commented on src/guide/transitions-overview.md
> +在下一节中，我们将回顾一些 web 动画和过渡的基础知识，并提供一些资源链接以进行进一步的研究。如果你已经熟悉 web 动画，并且了解这些原理如何与 Vue 的某些指令配合使用，可以跳过这一节。对于希望在开始学习之前进一步了解 web 动画基础知识的其他人，请继续阅读。
```suggestion
在下一节中，我们将回顾一些 web 动画和过渡的基础知识，并提供一些资源链接以进行进一步的研究。如果你已经熟悉 web 动画，并且了解这些原理如何与 Vue 的某些指令配合使用，可以跳过这一节。如果希望在开始学习之前进一步了解 web 动画基础知识，请继续阅读。
```

2021-12-04 17:15 UTC, Justineo commented on src/guide/transitions-overview.md
>  ## Timing
时长

2021-12-04 17:15 UTC, Justineo commented on src/guide/transitions-overview.md
>  ## Easing
我建议是看上下文来分别翻译为“缓动效果” / “缓动函数”，这里可能翻译成“缓动效果”好一些。

2021-12-04 17:15 UTC, Justineo commented on src/guide/transitions-overview.md
> +虽然使用 cubic-bezier ease 提供的两个控制句柄可以为简单的动画实现很好的效果，但是 JavaScript 允许多个控制句柄，以支持更多的变化。
```suggestion
虽然可以通过三次贝塞尔曲线提供的两个控制点为简单动画实现很好的效果，但 JavaScript 允许使用多个控制点，因此也支持更多的变化。
```

2021-12-04 17:15 UTC, Justineo commented on src/guide/transitions-overview.md
> +你可以通过调整你的 easing 来获得很多独特的效果，使你的动画非常时尚。CSS 允许你通过调整 cubic-bezier property 来修改 easing，Lea Verou 开发的[这个 playground](https://cubic-bezier.com/#.17,.67,.83,.67) 对探索这个问题非常有帮助。
```suggestion
你可以通过调整缓动函数来获得更多独特的效果，使动画非常炫酷。CSS 允许你通过调整三次贝塞尔曲线的参数来进行修改。Lea Verou 的[这个 playground](https://cubic-bezier.com/#.17,.67,.83,.67) 对探索这个问题非常有帮助。
```

2021-12-04 17:15 UTC, Justineo commented on src/guide/transitions-overview.md
> +easing 也可以表达动画元素的质量。以下面的 Pen 为例，你认为哪个球是硬的，哪个球是软的？
```suggestion
缓动效果也可以用来表达动画元素的材质。以下面的 pen 为例，你认为哪个球是硬的，哪个球是软的？
```

2021-12-05 01:37 UTC, wxsms commented on src/guide/transitions-overview.md
>  ## Easing
我觉得ok，其它篇章也有翻译为“缓动效果” / “缓动函数“的。

2021-12-05 01:37 UTC, wxsms commented on src/guide/transitions-overview.md
>  ## Timing
ok

2021-12-05 01:47 UTC, wxsms commented on src/guide/transitions-overview.md
>  ## Easing
已修改翻译

2021-12-05 01:50 UTC, wxsms commented on src/guide/transitions-overview.md
> +虽然使用 cubic-bezier ease 提供的两个控制句柄可以为简单的动画实现很好的效果，但是 JavaScript 允许多个控制句柄，以支持更多的变化。
这里我有一个疑问：cubic-bezier 这个词是否应该翻译呢？这个词貌似是特指 css 里面的 cubic-bezier 函数，请见：https://developer.mozilla.org/en-US/docs/Web/CSS/easing-function。

其余部分已apply。

2021-12-05 01:50 UTC, wxsms commented on src/guide/transitions-overview.md
> +你可以通过调整你的 easing 来获得很多独特的效果，使你的动画非常时尚。CSS 允许你通过调整 cubic-bezier property 来修改 easing，Lea Verou 开发的[这个 playground](https://cubic-bezier.com/#.17,.67,.83,.67) 对探索这个问题非常有帮助。
同上疑问，其余部分已apply。

2021-12-07 11:36 UTC, watonyweng approved these changes

2021-12-07 11:41 UTC, watonyweng commented on src/guide/transitions-overview.md
> +虽然使用 cubic-bezier ease 提供的两个控制句柄可以为简单的动画实现很好的效果，但是 JavaScript 允许多个控制句柄，以支持更多的变化。
cubic-bezier 建议不翻译

2021-12-09 02:42 UTC, Justineo commented on src/guide/transitions-overview.md
> +你可以通过调整你的 easing 来获得很多独特的效果，使你的动画非常时尚。CSS 允许你通过调整 cubic-bezier property 来修改 easing，Lea Verou 开发的[这个 playground](https://cubic-bezier.com/#.17,.67,.83,.67) 对探索这个问题非常有帮助。
严格来说这里是原文写错了，cubic-bezier 不是一个 property。或者这样：

> CSS 允许你通过调整 cubic-bezier 函数的参数来修改缓动效果。

2021-12-09 02:43 UTC, Justineo commented on src/guide/transitions-overview.md
> +虽然使用 cubic-bezier ease 提供的两个控制句柄可以为简单的动画实现很好的效果，但是 JavaScript 允许多个控制句柄，以支持更多的变化。
我个人倾向翻译，因为：我们只会说贝塞尔曲线有控制点，而不会说 cubic-bezier 函数有控制点。函数只有参数。

2021-12-09 02:55 UTC, wxsms commented on src/guide/transitions-overview.md
> +虽然使用 cubic-bezier ease 提供的两个控制句柄可以为简单的动画实现很好的效果，但是 JavaScript 允许多个控制句柄，以支持更多的变化。
已修改

2021-12-09 02:55 UTC, wxsms commented on src/guide/transitions-overview.md
> +你可以通过调整你的 easing 来获得很多独特的效果，使你的动画非常时尚。CSS 允许你通过调整 cubic-bezier property 来修改 easing，Lea Verou 开发的[这个 playground](https://cubic-bezier.com/#.17,.67,.83,.67) 对探索这个问题非常有帮助。
有道理，已修改，后续我给英文版也提一个PR。

2021-12-09 02:57 UTC, Justineo commented on src/guide/transitions-overview.md
> +我们将在之后章节的部分示例中使用 GreenSock。他们有一个很棒的 [缓动效果可视化工具](https://greensock.com/ease-visualizer)，帮助你建立精心制作的缓动效果。
```suggestion
我们将在之后章节的部分示例中使用 GreenSock。他们有一个很棒的[缓动效果可视化工具](https://greensock.com/ease-visualizer)，帮助你建立精心制作的缓动效果。
```

2021-12-09 02:58 UTC, merged

2021-12-09 03:05 UTC, wxsms commented on src/guide/transitions-overview.md
> +你可以通过调整你的 easing 来获得很多独特的效果，使你的动画非常时尚。CSS 允许你通过调整 cubic-bezier property 来修改 easing，Lea Verou 开发的[这个 playground](https://cubic-bezier.com/#.17,.67,.83,.67) 对探索这个问题非常有帮助。
https://github.com/vuejs/docs/pull/1373