update transitions-enterleave.md
vuejs/docs-next-zh-cn pull request #828
Opened 2021-11-30 04:53 UTC by wxsms

## Description of Problem

翻译修缮

2021-12-02 12:31 UTC, watonyweng approved these changes

2021-12-04 17:49 UTC, Justineo requested changes

2021-12-04 17:49 UTC, Justineo commented on src/guide/transitions-enterleave.md
> +/* 设置不同的持续时间和动画函数      */
```suggestion
/* 可以为进入和离开动画设置不同的持续时间和动画函数 */
```

2021-12-04 17:49 UTC, Justineo commented on src/guide/transitions-enterleave.md
> +他们的优先级高于普通的类名，这对于结合 Vue 的过渡系统和其他第三方 CSS 动画库，如 [Animate.css](https://daneden.github.io/animate.css/) 的用法十分有用。
```suggestion
它们的优先级高于普通的类名，当你希望将其它第三方 CSS 动画库与 Vue 的过度系统相结合时十分有用，比如 [Animate.css](https://daneden.github.io/animate.css/)。
```

2021-12-04 17:49 UTC, Justineo commented on src/guide/transitions-enterleave.md
>  通过添加一个 attribute，我们修复了原来的过渡，而不必添加任何特殊 style。
```suggestion
通过添加一个 attribute，我们修复了原来的过渡，而不必添加任何特殊样式。
```

2021-12-05 10:03 UTC, merged