sync #0fd3fff
vuejs/docs-next-zh-cn pull request #844
Opened 2021-12-17 08:01 UTC by wxsms

## Description of Problem

https://github.com/vuejs/docs/compare/4dfc045...0fd3fff

2021-12-17 09:35 UTC, watonyweng requested changes

2021-12-17 09:35 UTC, watonyweng commented on src/guide/migration/migration-build.md
> +- 服务端渲染：该迁移构建版本可以被用于服务端渲染，但是迁移一个自定义的服务端渲染设置有更多工作要做。大致的思路是将 `vue-server-renderer` 替换为 [`@vue/server-renderer`](https://github.com/vuejs/vue-next/tree/master/packages/server-renderer)。Vue 3 不再提供一个包渲染器，
该迁移构建版本可以被用于服务端渲染，但是迁移一个自定义的服务端渲染设置要做更多的工作。

2021-12-21 06:27 UTC, wxsms commented on src/guide/migration/migration-build.md
> +- 服务端渲染：该迁移构建版本可以被用于服务端渲染，但是迁移一个自定义的服务端渲染设置有更多工作要做。大致的思路是将 `vue-server-renderer` 替换为 [`@vue/server-renderer`](https://github.com/vuejs/vue-next/tree/master/packages/server-renderer)。Vue 3 不再提供一个包渲染器，
这个我觉得原翻译没有问题，可以看看其它人的意见。谢谢。

2021-12-23 15:13 UTC, veaba commented on src/guide/migration/migration-build.md
> +- 服务端渲染：该迁移构建版本可以被用于服务端渲染，但是迁移一个自定义的服务端渲染设置有更多工作要做。大致的思路是将 `vue-server-renderer` 替换为 [`@vue/server-renderer`](https://github.com/vuejs/vue-next/tree/master/packages/server-renderer)。Vue 3 不再提供一个包渲染器，
```suggestion
- 服务端渲染：该迁移构建版本可以被用于服务端渲染，但是迁移一个自定义的服务端渲染配置还有很多工作要做。大致的思路是将 `vue-server-renderer` 替换为 [`@vue/server-renderer`](https://github.com/vuejs/vue-next/tree/master/packages/server-renderer)。Vue 3 不再提供一个包渲染器，且我们推荐使用 [Vite](https://cn.vitejs.dev/guide/ssr.html) 以支持 Vue 3 服务端渲染。如果你正在使用 [Nuxt.js](https://zh.nuxtjs.org/)，可以尝试 [Nuxt Bridge，一个 Nuxt.js 2 到 3 的兼容层](https://v3.nuxtjs.org/getting-started/bridge/)。对于复杂、生产环境的项目来说，可能最好还是等待一下 [Nuxt 3 (目前处于 beta 阶段)](https://v3.nuxtjs.org/getting-started/introduction)。
```
setup 有点怪怪的，译为设置

2021-12-24 07:17 UTC, veaba approved these changes

2021-12-24 07:18 UTC, merged