Update template-syntax.md
vuejs/docs-next-zh-cn pull request #845
Opened 2021-12-19 09:54 UTC by ekkoyr

## 翻译好像有点问题

## Proposed Solution

## Additional Information

2021-12-20 01:12 UTC, wxsms requested changes

2021-12-20 01:12 UTC, wxsms commented on src/guide/template-syntax.md
> +动态参数预期会求出一个字符串， `null`例外。这个特殊的 `null` 值可以被显性地用于移除绑定。任何其它非字符串类型的值都将会触发一个警告。
```suggestion
动态参数预期会求出一个字符串， `null` 例外。这个特殊的 `null` 值可以被显性地用于移除绑定。任何其它非字符串类型的值都将会触发一个警告。
```

2021-12-21 01:08 UTC, wxsms approved these changes

2021-12-21 01:47 UTC, merged

2021-12-31 03:40 UTC, Jinjiang commented on src/guide/template-syntax.md
> +动态参数预期会求出一个字符串， `null` 例外。这个特殊的 `null` 值可以用于显式地移除绑定。任何其它非字符串类型的值都将会触发一个警告。
```
动态参数预期会求出一个字符串， `null` 例外。
```

null 前面多了一个不必要的空格

2021-12-31 06:16 UTC, wxsms commented on src/guide/template-syntax.md
> +动态参数预期会求出一个字符串， `null` 例外。这个特殊的 `null` 值可以用于显式地移除绑定。任何其它非字符串类型的值都将会触发一个警告。
已修复：https://github.com/vuejs/docs-next-zh-cn/pull/854